### ISSUE TITLE
Using a custom dns in aws. Getting getaddrinfo: Name does not resolve for splunk-kubernetes-metrics

### ISSUE THREAD

**Issue by bearmoo-repo** [splunk/splunk-connect-for-kubernetes#117]
So, I got the logging working and I'm trying to get the metrics stuff working as well. Unfortunately, were using custom dns on our aws vpc where ip-10-99-2-120.us-west-2.compute.internal does not resolved. Is there a way to get around this? Maybe connect to ip address only?

Error message:
2019-03-26 17:14:10 +0000 [error]: #0 Timer detached. title=:stats_metric_scraper
2019-03-26 17:14:10 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=SocketError error="Failed to open TCP connection to 10-99-2-120.us-west-2.compute.internal:10250 (getaddrinfo: Name does not resolve)"
  2019-03-26 17:14:10 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-03-26 17:14:10 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-03-26 17:14:10 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-03-26 17:14:10 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-03-26 17:14:10 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-03-26 17:14:10 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2019-03-26 17:14:10 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'

**Comment by bearmoo-repo** [comment]
Looking at this a little closer:

kubectl exec -it -n splunk-connect-k8s splunk-connect-splunk-kubernetes-metrics-z8qlt /bin/sh
I've notice that in /etc/hosts
/ # cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.99.2.120     splunk-connect-splunk-kubernetes-metrics-z8qlt

if the pod has the node ip in hosts? Would it be possible to have splunk metrics resolve on its self?

-Frank

**Comment by bearmoo-repo** [comment]
Opps, sorry splunk pod the nodes secondary ip instead.

**Comment by matthewmodestino** [comment]
I saw this with another customer on EKS. Any chance you are using terraform to deploy the VPC?

**Comment by bearmoo-repo** [comment]
No, I'm not using terraform to create/manage eks. I'm used the guild:

https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html

Would I need to still apply the enable_dns_hostnames?

-Frank

**Comment by matthewmodestino** [comment]
What is guild?

I run on eks getting started example with no issues.

The main item is that the pod needs to be able to resolve and reach the AWS node. So double check your dns strategy and make sure you can resolve the node fqdn

**Comment by matthewmodestino** [comment]
i just noticed the ip trying to be resolved is the IP of your metrics pod?? Thats incorrect. It should be the IP/hostname of the ec2 instance.

Please post your metrics daemonset configmap. 

`kubectl logs <yourPod>`

We dump the running config at startup.

**Comment by bearmoo-repo** [comment]
Hi matthewmodestino,

Sorry, that's a typo, I meant user guide for the setting up eks in aws. I used helm to setup Splunk connector for Kubernetes. 

kubectl logs -n splunk-connect-k8s splunk-connect-splunk-kubernetes-metrics-vzd9e
chown: /fluentd/etc/splunk/..data: Read-only file system
chown: /fluentd/etc/splunk/splunk_hec_token: Read-only file system
chown: /fluentd/etc/splunk/..2019_03_26_22_14_54.036422611/splunk_hec_token: Read-only file system
chown: /fluentd/etc/splunk/..2019_03_26_22_14_54.036422611: Read-only file system
chown: /fluentd/etc/splunk/..2019_03_26_22_14_54.036422611: Read-only file system
chown: /fluentd/etc/splunk: Read-only file system
chown: /fluentd/etc/splunk: Read-only file system
chown: /fluentd/etc/..2019_03_26_22_14_54.703124349/fluent.conf: Read-only file system
chown: /fluentd/etc/..2019_03_26_22_14_54.703124349: Read-only file system
chown: /fluentd/etc/..2019_03_26_22_14_54.703124349: Read-only file system
chown: /fluentd/etc/fluent.conf: Read-only file system
chown: /fluentd/etc/..data: Read-only file system
chown: /fluentd/etc: Read-only file system
chown: /fluentd/etc: Read-only file system
2019-03-27 05:25:54 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2019-03-27 05:25:56 +0000 [info]: Use URL https://10-99-2-120.us-west-2.compute.internal:10250/stats/summary for creating client to query kubelet summary api
2019-03-27 05:25:56 +0000 [info]: Use URL https://10-99-2-120.us-west-2.compute.internal:10250/stats/ for creating client to query kubelet stats api
2019-03-27 05:25:56 +0000 [info]: Use URL https://10-99-2-120.us-west-2.compute.internal:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-03-27 05:25:56 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics
    tag "kube.*"
    node_name "10-99-2-120.us-west-2.compute.internal"
    use_rest_client_ssl true
    cluster_name cluster_name
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name cluster_name
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol http
    hec_host "splunk.example.com"
    hec_port 8088
    hec_token "ddd-xxx-yyy"
    host "10-99-2-120.us-west-2.compute.internal"
    index "eks_metrics"
    source "${tag}"
    insecure_ssl true
    <buffer>
      @type "memory"
      chunk_limit_records 1e+06
      chunk_limit_size 100m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 3
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>
2019-03-27 05:25:56 +0000 [info]: starting fluentd-1.4.0 pid=5 ruby="2.5.2"
2019-03-27 05:25:56 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2019-03-27 05:25:59 +0000 [info]: gem 'fluent-plugin-kubernetes-metrics' version '1.1.0'
2019-03-27 05:25:59 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-03-27 05:25:59 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.1.0'
2019-03-27 05:25:59 +0000 [info]: gem 'fluentd' version '1.4.0'
2019-03-27 05:25:59 +0000 [info]: gem 'fluentd' version '1.3.3'
2019-03-27 05:25:59 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2019-03-27 05:25:59 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2019-03-27 05:25:59 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2019-03-27 05:25:59 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2019-03-27 05:25:59 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2019-03-27 05:25:59 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2019-03-27 05:26:00 +0000 [info]: adding source type="kubernetes_metrics"
2019-03-27 05:26:01 +0000 [info]: #0 Use URL https://10-99-2-120.us-west-2.compute.internal:10250/stats/summary for creating client to query kubelet summary api
2019-03-27 05:26:01 +0000 [info]: #0 Use URL https://10-99-2-120.us-west-2.compute.internal:10250/stats/ for creating client to query kubelet stats api
2019-03-27 05:26:01 +0000 [info]: #0 Use URL https://10-99-2-120.us-west-2.compute.internal:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-03-27 05:26:01 +0000 [warn]: parameter 'cluster_name' in <source>
  @type kubernetes_metrics
  tag "kube.*"
  node_name "10-99-2-120.us-west-2.compute.internal"
  use_rest_client_ssl true
  cluster_name cluster_name
</source> is not used.
2019-03-27 05:26:01 +0000 [info]: #0 starting fluentd worker pid=15 ppid=5 worker=0
2019-03-27 05:26:01 +0000 [info]: #0 fluentd worker is now running worker=0
2019-03-27 05:26:16 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=SocketError error="Failed to open TCP connection to 10-99-2-120.us-west-2.compute.internal:10250 (getaddrinfo: Name does not resolve)"
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:608:in `scrape_metrics'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-03-27 05:26:16 +0000 [error]: #0 Timer detached. title=:metric_scraper
2019-03-27 05:26:16 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=SocketError error="Failed to open TCP connection to 10-99-2-120.us-west-2.compute.internal:10250 (getaddrinfo: Name does not resolve)"
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:620:in `scrape_stats_metrics'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-03-27 05:26:16 +0000 [error]: #0 Timer detached. title=:stats_metric_scraper
2019-03-27 05:26:16 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=SocketError error="Failed to open TCP connection to 10-99-2-120.us-west-2.compute.internal:10250 (getaddrinfo: Name does not resolve)"
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:633:in `scrape_cadvisor_metrics'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-03-27 05:26:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-03-27 05:26:16 +0000 [error]: #0 Timer detached. title=:cadvisor_metric_scraper

**Comment by matthewmodestino** [comment]
Ok, so this looks ok at first glance. i think you’ll need to review your DNS setup and make sure the ec2 fqdn can be resolved.

**Comment by bearmoo-repo** [comment]
Is there a way where I can tell splunk-connector-kubernetes to talk to the host by ip instead?

**Comment by matthewmodestino** [comment]
you would have to edit the deployment.yaml template to grab the host ip, instead of the hostname:

```
containers:
      - name: splunk-fluentd-k8s-metrics
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: SPLUNK_HEC_HOST
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
```

Not sure if that will work or not...i’d still encourage you to figure out what’s up with DNS...

**Comment by matthewmodestino** [comment]
any update on this, Frank?

**Comment by bearmoo-repo** [comment]
Ok, So it looks like I can get it to work. On the second video on https://www.splunk.com/blog/2018/07/19/splunk-connect-for-kubernetes-on-eks.html. It showed metrics. I was wondering if that was a plugin, or is the documentation on how to get that options?

**Comment by sfrancies** [comment]
Hi, I am facing similar issues with AKS, Could you please guide on how to fix this ?

**Comment by sfrancies** [comment]
I am able to update the deployment.yaml to grab the hostIP, but now I get SSL Certificate Not Verified error below

#0 Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=RestClient::SSLCertificateNotVerified error="SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (self signed certificate in certificate chain)"

Tried adding insecuressl value to true in the values.yaml during deployment, but still same error
kubernetes:
  insecureSSL: true

**Comment by matthewmodestino** [comment]
Hey @bearmoo-repo, Splunk Connect for Kubernetes includes collection for logs, metrics and metadata! 

Check out the manifest folder to see each deployment and configs:https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/manifests

@sfrancies can you share your metrics values?

I use this currently on eks:

```
#local config for metrics chart
splunk-kubernetes-metrics:
  kubernetes:
    clusterName: eks
    kubeletPort: 10250
    useRestClientSSL: true
    insecureSSL: true
  buffer:
    chunk_limit_records: 10000
  aggregatorBuffer:
    chunk_limit_records: 10000
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: eks_metrics
```

I would suggest ssh'ing into one of your nodes and confirming the kubelet port and the configs being used...almost looks like it's not using ssl??

**Comment by sfrancies** [comment]
I am able to use port 10255 setting useRestClientSSL to false and forward metrics

**Comment by chaitanyaphalak** [comment]
@sfrancies I hope you have resolved your issues with AKS and EKS. Please let us know if you need help. Thanks.
