### ISSUE TITLE
Azure AKS. splunk-kubernetes-metric issue. SocketError error="Failed to open TCP connection.."

### ISSUE THREAD

**Issue by DmitriyDranenkoDevPro** [splunk/splunk-connect-for-kubernetes#126]
Hi,
I've faced the issue with getting kubernetes-metric into Splunk

metrics pods have the following errors in logs

Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=SocketError error="Failed to open TCP connection to aks-nodepool1-21705401-0:10250 (getaddrinfo: Try again)"

Ater helm deployment I see following pods:

```
kubectl get pods -n splunk -o wide

NAME                                                              READY     STATUS    RESTARTS   AGE       IP             NODE

splunk-connect-for-kubernetes-splunk-kubernetes-logging-cs96v     1/1       Running   0          1h        10.11.16.11    aks-nodepool1-21705401-1
splunk-connect-for-kubernetes-splunk-kubernetes-logging-vrlqz     1/1       Running   0          1h        10.11.16.205   aks-nodepool1-21705401-2
splunk-connect-for-kubernetes-splunk-kubernetes-logging-xj62v     1/1       Running   0          1h        10.11.16.119   aks-nodepool1-21705401-0
splunk-connect-for-kubernetes-splunk-kubernetes-metrics-agcsgmn   1/1       Running   1          1h        10.11.16.62    aks-nodepool1-21705401-1
splunk-connect-for-kubernetes-splunk-kubernetes-metrics-gbnqn     1/1       Running   0          1h        10.11.16.25    aks-nodepool1-21705401-1
splunk-connect-for-kubernetes-splunk-kubernetes-metrics-vz9bc     1/1       Running   0          1h        10.11.16.101   aks-nodepool1-21705401-0
splunk-connect-for-kubernetes-splunk-kubernetes-metrics-wf6mv     1/1       Running   0          1h        10.11.16.183   aks-nodepool1-21705401-2
splunk-connect-for-kubernetes-splunk-kubernetes-objects-85w7fht   1/1       Running   0          1h        10.11.16.12    aks-nodepool1-21705401-1
```

But looks like splunk-connect-metric pods don't work

As example:
kubectl logs -n splunk splunk-connect-for-kubernetes-splunk-kubernetes-metrics-vz9bc

```
chown: /fluentd/etc/splunk/..data: Read-only file system
chown: /fluentd/etc/splunk/splunk_hec_token: Read-only file system
chown: /fluentd/etc/splunk/..2019_04_10_13_36_46.428143669/splunk_hec_token: Read-only file system
chown: /fluentd/etc/splunk/..2019_04_10_13_36_46.428143669: Read-only file system
chown: /fluentd/etc/splunk/..2019_04_10_13_36_46.428143669: Read-only file system
chown: /fluentd/etc/splunk: Read-only file system
chown: /fluentd/etc/splunk: Read-only file system
chown: /fluentd/etc/..2019_04_10_13_36_46.521055760/fluent.conf: Read-only file system
chown: /fluentd/etc/..2019_04_10_13_36_46.521055760: Read-only file system
chown: /fluentd/etc/..2019_04_10_13_36_46.521055760: Read-only file system
chown: /fluentd/etc/fluent.conf: Read-only file system
chown: /fluentd/etc/..data: Read-only file system
chown: /fluentd/etc: Read-only file system
chown: /fluentd/etc: Read-only file system
2019-04-10 13:36:52 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2019-04-10 13:36:54 +0000 [info]: Use URL http://aks-nodepool1-21705401-0:10250/stats/summary for creating client to query kubelet summary api
2019-04-10 13:36:54 +0000 [info]: Use URL http://aks-nodepool1-21705401-0:10250/stats/ for creating client to query kubelet stats api
2019-04-10 13:36:54 +0000 [info]: Use URL http://aks-nodepool1-21705401-0:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-04-10 13:36:54 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics
    tag "kube.*"
    node_name "aks-nodepool1-21705401-0"
    use_rest_client_ssl false
    cluster_name dev-qa-aks
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name dev-qa-aks
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "index01.splunk.xxxxxxxxx.xxx"
    hec_port 8088
    hec_token "df80af5c-160f-462e-bd68-57e33f48a111"
    host "aks-nodepool1-21705401-0"
    index "dev-metric"
    source "${tag}"
    insecure_ssl false
    <buffer>
      @type "memory"
      chunk_limit_records 1e+06
      chunk_limit_size 100m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 3
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>
2019-04-10 13:36:54 +0000 [info]: starting fluentd-1.4.0 pid=6 ruby="2.5.2"
2019-04-10 13:36:54 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2019-04-10 13:36:57 +0000 [info]: gem 'fluent-plugin-kubernetes-metrics' version '1.1.0'
2019-04-10 13:36:57 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-04-10 13:36:57 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.1.0'
2019-04-10 13:36:57 +0000 [info]: gem 'fluentd' version '1.4.0'
2019-04-10 13:36:57 +0000 [info]: gem 'fluentd' version '1.3.3'
2019-04-10 13:36:57 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2019-04-10 13:36:57 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2019-04-10 13:36:57 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2019-04-10 13:36:57 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2019-04-10 13:36:57 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2019-04-10 13:36:57 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2019-04-10 13:36:57 +0000 [info]: adding source type="kubernetes_metrics"
2019-04-10 13:36:59 +0000 [info]: #0 Use URL http://aks-nodepool1-21705401-0:10250/stats/summary for creating client to query kubelet summary api
2019-04-10 13:36:59 +0000 [info]: #0 Use URL http://aks-nodepool1-21705401-0:10250/stats/ for creating client to query kubelet stats api
2019-04-10 13:36:59 +0000 [info]: #0 Use URL http://aks-nodepool1-21705401-0:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-04-10 13:36:59 +0000 [warn]: parameter 'cluster_name' in <source>
  @type kubernetes_metrics
  tag "kube.*"
  node_name "aks-nodepool1-21705401-0"
  use_rest_client_ssl false
  cluster_name dev-qa-aks
</source> is not used.
2019-04-10 13:36:59 +0000 [info]: #0 starting fluentd worker pid=16 ppid=6 worker=0
2019-04-10 13:36:59 +0000 [info]: #0 fluentd worker is now running worker=0
2019-04-10 13:37:19 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=SocketError error="Failed to open TCP connection to aks-nodepool1-21705401-0:10250 (getaddrinfo: Try again)"
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:608:in `scrape_metrics'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-04-10 13:37:19 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-04-10 13:37:19 +0000 [error]: #0 Timer detached. title=:metric_scraper
2019-04-10 13:37:24 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=SocketError error="Failed to open TCP connection to aks-nodepool1-21705401-0:10250 (getaddrinfo: Try again)"
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:620:in `scrape_stats_metrics'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-04-10 13:37:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-04-10 13:37:24 +0000 [error]: #0 Timer detached. title=:stats_metric_scraper
2019-04-10 13:37:29 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=SocketError error="Failed to open TCP connection to aks-nodepool1-21705401-0:10250 (getaddrinfo: Try again)"
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:633:in `scrape_cadvisor_metrics'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-04-10 13:37:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-04-10 13:37:29 +0000 [error]: #0 Timer detached. title=:cadvisor_metric_scraper

```

although another metric "aggregate" pod doesn't have such errors:

kubectl logs -n splunk splunk-connect-for-kubernetes-splunk-kubernetes-metrics-agc
sgmn 
it connects to K8S API server address with nodes name. 

```
2019-04-10 14:42:18 +0000 [info]: #0 Use URL https://xxxx-aks-cluster-eus-041d98dc.hcp.eastus.azmk8s.io/api/v1/nodes/aks-nodepool1-21705401-0:10250/proxy/stats/summary for scraping resource usage metrics
2019-04-10 14:42:18 +0000 [info]: #0 Use URL https://xxxx-aks-cluster-eus-041d98dc.hcp.eastus.azmk8s.io/api/v1/nodes/aks-nodepool1-21705401-1:10250/proxy/stats/summary for scraping resource usage metrics
2019-04-10 14:42:18 +0000 [info]: #0 Use URL https://xxxx-aks-cluster-eus-041d98dc.hcp.eastus.azmk8s.io/api/v1/nodes/aks-nodepool1-21705401-2:10250/proxy/stats/summary for scraping resource usage metrics
```

**Comment by matthewmodestino** [comment]
Hi! 

I have seen some users have issues surrounding dns resolution of the nodeName field. 

```
      @type kubernetes_metrics
      tag kube.*
      node_name "#{ENV['SPLUNK_HEC_HOST']}"
      use_rest_client_ssl true
      cluster_name cluster_name

```

It comes from the deployment/daemonset yamls, and may not resolve or be configured in your DNS. Can you confirm? Other customers have been able to work around it by setting the variable to IP or configuring their environment to ensure the node name can be resolved. 

While checking, I would also confirm the port the kubelet is serving on for your nodes. Some deploys may have 10255, some may have 10250, and the ssl configs may need customization. 

Let me know what you find!

**Comment by DmitriyDranenkoDevPro** [comment]
You were right, 
I've changed the default value for kubeletPort to10255, and also changed {ENV['SPLUNK_HEC_HOST'] value from spec.nodeName to status.hostIP in splunk-kubernetes-metrics deployment.yaml env block.

```
        env:
          - name: SPLUNK_HEC_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP 
          - name: SPLUNK_HEC_TOKEN
```

This was fixed my issue.

**Comment by matthewmodestino** [comment]
Awesome! Please be sure to also set the `buffer_chunk_limit` as described here:

https://github.com/splunk/splunk-connect-for-kubernetes/issues/107
