### ISSUE TITLE
kubernetes_metrics Unexpected error raised....RestClient::Unauthorized error="401 Unauthorized"

### ISSUE THREAD

**Issue by hhagewood** [splunk/splunk-connect-for-kubernetes#128]
I am facing this issue with only the Metrics collector.  the logs and objects seem to be coming in fine and no error in the logs following helm deploy.

2019-04-12 12:57:12 +0000 [info]: #0 Use URL https://aks-agentpool-33848038-3:10250/stats/summary for creating client to query kubelet summary api
2019-04-12 12:57:12 +0000 [info]: #0 Use URL https://aks-agentpool-33848038-3:10250/stats/ for creating client to query kubelet stats api
2019-04-12 12:57:12 +0000 [info]: #0 Use URL https://aks-agentpool-33848038-3:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-04-12 12:57:12 +0000 [warn]: parameter 'cluster_name' in <source>
  "@"type kubernetes_metrics
  tag "kube.*"
  node_name "aks-agentpool-33848038-3"
  kubelet_port 10250
  use_rest_client_ssl true
  insecure_ssl true
  cluster_name Kube-Splunk-Test
</source> is not used.
2019-04-12 12:57:12 +0000 [info]: #0 starting fluentd worker pid=17 ppid=7 worker=0
2019-04-12 12:57:12 +0000 [info]: #0 fluentd worker is now running worker=0
**2019-04-12 12:57:27 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=RestClient::Unauthorized error="401 Unauthorized"**
  2019-04-12 12:57:27 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
  2019-04-12 12:57:27 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
  2019-04-12 12:57:27 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
  2019-04-12 12:57:27 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
  2019-04-12 12:57:27 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:910:in `start'

**Comment by sfrancies** [comment]
I had a similar problem, but when I used port 10255 and set useRestClientSSL: false it worked

splunk-kubernetes-metrics:
  kubernetes:
    insecureSSL: true
    kubeletPort: 10255
    useRestClientSSL: false
  buffer:
    chunk_limit_records: 10000
  aggregatorBuffer:
    chunk_limit_records: 10000

**Comment by hhagewood** [comment]
Thanks @sfrancies, was that in AKS or GKE ?  I still get refused but not with an SSL error.

**Comment by sfrancies** [comment]
AKS, whats the error ?
10255 is insecure port so shouldnt see SSL error

**Comment by hhagewood** [comment]
Thanks @sfrancies, I updated and redeployed with this below for the metrics section and the 'HTTP 401' and SSL errors went away but eventhough there are no more errors for the metric pods there are still no metrics in my index alongside the Objects and Logging detail being ingested :(

#local config for metrics chart
splunk-kubernetes-metrics:
  kubernetes:
    clusterName: Kube-Splunk-Test
    kubeletPort: 10255
    useRestClientSSL: false
    insecureSSL: true
  buffer:
    chunk_limit_records: 10000
  aggregatorBuffer:
    chunk_limit_records: 10000
  splunk:
    hec:
      port: 443
      indexName: k8s-metrics-index

**Comment by yarinm** [comment]
I had the same issue, is there any way we can make this work while enabling SSL ?

**Comment by chaitanyaphalak** [comment]
AKS uses self signed certificates for creating kubernetes clusters, so unfortunately we can only use insecure mode.

**Comment by beth2016** [comment]
@hhagewood i am geting the same error.  I saw you had closed this issue.   Did you find the resolution?
