### ISSUE TITLE
Support AKS RBAC metrics

### ISSUE THREAD

**Issue by cwebbtw** [splunk/splunk-connect-for-kubernetes#171]
**What would you like to be added**:

Support for RBAC enabled AKS cluster.

Currently when scraping from kubelet on 10250 on Kubernetes 1.13.5 (AKS), the metrics pod is returning a 401 Unauthorized.

See:

```
2019-06-12 15:56:47 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=RestClient::Unauthorized error="401 Unauthorized"
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/2.5.0/net/http.rb:910:in `start'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:633:in `scrape_cadvisor_metrics'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-06-12 15:56:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-06-12 15:56:47 +0000 [error]: #0 Timer detached. title=:cadvisor_metric_scraper
```

Port 10225 is disabled by default so SSL is the only option.

Below shows the flags for how kubelet is started:

```
I0522 11:51:58.643780   15035 flags.go:33] FLAG: --allow-privileged="true"
I0522 11:51:58.643787   15035 flags.go:33] FLAG: --allowed-unsafe-sysctls="[]"
I0522 11:51:58.643796   15035 flags.go:33] FLAG: --alsologtostderr="false"
I0522 11:51:58.643801   15035 flags.go:33] FLAG: --anonymous-auth="false"
I0522 11:51:58.643804   15035 flags.go:33] FLAG: --application-metrics-count-limit="100"
I0522 11:51:58.643808   15035 flags.go:33] FLAG: --authentication-token-webhook="false"
I0522 11:51:58.643811   15035 flags.go:33] FLAG: --authentication-token-webhook-cache-ttl="2m0s"
I0522 11:51:58.643820   15035 flags.go:33] FLAG: --authorization-mode="Webhook"
I0522 11:51:58.643824   15035 flags.go:33] FLAG: --authorization-webhook-cache-authorized-ttl="5m0s"
I0522 11:51:58.643828   15035 flags.go:33] FLAG: --authorization-webhook-cache-unauthorized-ttl="30s"
```

**Why is this needed**:

Support for RBAC enabled AKS cluster.

**Comment by chaitanyaphalak** [comment]
Nice catch @cwebbtw. We haven't tested this release on AKS. We will tackle the RBAC issues when supporting AKS. Thanks. 
Meanwhile if you have time to experiment you can try using the cluster roles on this page https://kubernetes.io/docs/reference/access-authn-authz/rbac/ to get yourself unblocked. AFAIK cluster-admin role will work for sure. After that, you can try to find a less permissive one which works with AKS.
Please report your findings back to us. Thanks.

**Comment by cwebbtw** [comment]
After fiddling around, I was able to get the non ssl read only kubelet api working with splunk connect for kubernetes but actually it seems more that even with extremely permissive roles, the ssl port is unauthorised.

**Comment by chaitanyaphalak** [comment]
@cwebbtw that is interesting.I am glad non ssl kubelet api works for you. I havent looked at AKS for ssl kubelet API support. Maybe there are some cluster settings need to be tweaked. Let me know if you find out something relevant. Thanks :)

**Comment by chaitanyaphalak** [comment]
AKS uses self signed certificates for creating kubernetes clusters, so unfortunately we can only use insecure mode. Let us know if you find a workaround.
