### ISSUE TITLE
Not Seeing Metrics Data in Splunk Cloud Index

### ISSUE THREAD

**Issue by BobWieberdink** [splunk/splunk-connect-for-kubernetes#201]
What happened:
Not seeing metrics data in Splunk Cloud when implementing Splunk Connect for Kubernetes. We are however able to see log and object data. Seeing the following in the metrics pod logs:

2019-07-23 15:44:57 +0000 [debug]: #0 [Response] POST https://http-inputs-<redacted>.splunkcloud.com/services/collector: #<Net::HTTPOK 200 OK readbody=true>
2019-07-23 15:45:12 +0000 [debug]: #0 Received new chunk, size=1046393
2019-07-23 15:45:12 +0000 [debug]: #0 Sending 1046393 bytes to Splunk.
2019-07-23 15:45:23 +0000 [debug]: #0 [Response] POST https://http-inputs-<redacted>.splunkcloud.com/services/collector: #<Net::HTTPOK 200 OK readbody=true>
2019-07-23 15:45:26 +0000 [debug]: #0 Received new chunk, size=1046240
2019-07-23 15:45:26 +0000 [debug]: #0 Sending 1046240 bytes to Splunk.
2019-07-23 15:45:27 +0000 [debug]: #0 [Response] POST https://http-inputs-<redacted>.splunkcloud.com/services/collector: #<Net::HTTPOK 200 OK readbody=true>
2019-07-23 15:45:40 +0000 [debug]: #0 Received new chunk, size=1047250
2019-07-23 15:45:40 +0000 [debug]: #0 Sending 1047250 bytes to Splunk.
2019-07-23 15:45:48 +0000 [debug]: #0 [Response] POST https://http-inputs-<redacted>.splunkcloud.com/services/collector: #<Net::HTTPOK 200 OK readbody=true>
2019-07-23 15:45:57 +0000 [debug]: #0 Received new chunk, size=1047460
2019-07-23 15:45:57 +0000 [debug]: #0 Sending 1047460 bytes to Splunk.
2019-07-23 15:46:07 +0000 [debug]: #0 taking back chunk for errors. chunk="58e5b164f15e9a50596c723c5ca003d1"
2019-07-23 15:46:07 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-07-23 15:46:08 +0000 chunk="58e5b164f15e9a50596c723c5ca003d1" error_class=SocketError error="Failed to open TCP connection to http-inputs-<DEDACTED>.splunkcloud.com:443 (getaddrinfo: Try again)"
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:1541:in `begin_transport'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:1493:in `transport_request'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:1467:in `request'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:951:in `block in request'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:648:in `connection_for'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:945:in `request'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-splunk-hec-1.1.0/lib/fluent/plugin/out_splunk_hec.rb:355:in `send_to_hec'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-splunk-hec-1.1.0/lib/fluent/plugin/out_splunk_hec.rb:167:in `write'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-07-23 15:46:07 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-07-23 15:46:08 +0000 [debug]: #0 Received new chunk, size=1047460
2019-07-23 15:46:08 +0000 [debug]: #0 Sending 1047460 bytes to Splunk.
2019-07-23 15:46:11 +0000 [debug]: #0 [Response] POST https://http-inputs-<redacted>.splunkcloud.com/services/collector: #<Net::HTTPOK 200 OK readbody=true>
2019-07-23 15:46:11 +0000 [warn]: #0 retry succeeded. chunk_id="58e5b164f15e9a50596c723c5ca003d1"
2019-07-23 15:46:12 +0000 [debug]: #0 Received new chunk, size=1123692
2019-07-23 15:46:12 +0000 [debug]: #0 Sending 1123692 bytes to Splunk.
2019-07-23 15:46:12 +0000 [debug]: #0 [Response] POST https://http-inputs-<redacted>.splunkcloud.com/services/collector: #<Net::HTTPOK 200 OK readbody=true>
2019-07-23 15:46:25 +0000 [debug]: #0 Received new chunk, size=1130330
2019-07-23 15:46:25 +0000 [debug]: #0 Sending 1130330 bytes to Splunk.
2019-07-23 15:46:28 +0000 [debug]: #0 [Response] POST https://http-inputs-<redacted>.splunkcloud.com/services/collector: #<Net::HTTPOK 200 OK readbody=true>

What you expected to happen:

It looks like from the metrics pod logs that some posts to Splunk Cloud work and others do not. We are also not seeing any data in the metrics index in Splunk Could. Since the HEC connection is a global setting, is there a setting we need to add to the metrics collector? Is there something specific with posts that do not work that needs to be accounted for in the Helm template?

How to reproduce it (as minimally and precisely as possible):

Install Splunk Connect for Kubernetes with Helm with the following values yaml:

global:
  logLevel: debug
  splunk:
    hec:
      protocol: https
      insecureSSL: false
      host: http-inputs-<redacted>.splunkcloud.com
      token: <redacted>
      port: 443
splunk-kubernetes-logging:
  journalLogPath: /run/log/journal
  splunk:
    hec:
      indexName: <redacted>-log
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: false
  objects:
    core:
      v1:
        - name: pods
          interval: 30s
        - name: namespaces
          interval: 30s
        - name: nodes
          interval: 30s
        - name: services
          interval: 30s
        - name: config_maps
          interval: 30s
        - name: persistent_volumes
          interval: 30s
        - name: service_accounts
          interval: 30s
        - name: persistent_volume_claims
          interval: 30s
        - name: resource_quotas
          interval: 30s
        - name: component_statuses
          interval: 30s
        - name: events
          mode: watch
    apps:
      v1:
        - name: deployments
          interval: 30s
        - name: daemon_sets
          interval: 30s
        - name: replica_sets
          interval: 30s
        - name: stateful_sets
          interval: 30s
  splunk:
    hec:
      indexName: <redacted>-objects
splunk-kubernetes-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: <redacted>-metrics

Helm command  - helm install --name k8-connect splunk-connect-for-kubernetes-1.2.0.tgz --namespace test3 -f values.yaml

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version):1.13-EKS
OS (e.g: cat /etc/os-release):amazonlinux
Splunk version:
Others:

**Comment by chaitanyaphalak** [comment]
Is the index you created for metrics of the type "metric" ?

**Comment by BobWieberdink** [comment]
Looks like the formatting of the values file didn't come through in the last post, so here it is again....
global:
  logLevel: debug
  splunk:
    hec:
      protocol: https
      insecureSSL: false
      host: http-inputs-companyname.splunkcloud.com
      token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      port: 443
splunk-kubernetes-logging:
  journalLogPath: /run/log/journal
  splunk:
    hec:
      indexName: index-log
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: false
  objects:
    core:
      v1:
        - name: pods
          interval: 30s
        - name: namespaces
          interval: 30s
        - name: nodes
          interval: 30s
        - name: services
          interval: 30s
        - name: config_maps
          interval: 30s
        - name: persistent_volumes
          interval: 30s
        - name: service_accounts
          interval: 30s
        - name: persistent_volume_claims
          interval: 30s
        - name: resource_quotas
          interval: 30s
        - name: component_statuses
          interval: 30s
        - name: events
          mode: watch
    apps:
      v1:
        - name: deployments
          interval: 30s
        - name: daemon_sets
          interval: 30s
        - name: replica_sets
          interval: 30s
        - name: stateful_sets
          interval: 30s
  splunk:
    hec:
      indexName: index-objects
splunk-kubernetes-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: index-metrics

**Comment by chaitanyaphalak** [comment]
Is the index you created for metrics of the type "metric" ?
also can you try the following for metrics
splunk-kubernetes-metrics:
  splunk:
    hec:
      indexName: index-metrics
  kubernetes:
      insecureSSL: true
      useRestClientSSL: true
      kubeletPort: 10250

**Comment by matthewmodestino** [comment]
looks like hec config

let's doublecheck this:

```
2019-07-23 15:46:07 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-07-23 15:46:08 +0000 chunk="58e5b164f15e9a50596c723c5ca003d1" error_class=SocketError error="Failed to open TCP connection to http-inputs-.splunkcloud.com:443 (getaddrinfo: Try again)"
```

Is splunk cloud http or https? also is the url broken in the configmap for the pod?

**Comment by BobWieberdink** [comment]
I verified the index is of type "metric" with our Splunk Cloud admin and I am now able to see at least some data in the index. I am however still seeing the following messages in the container log:

2019-07-24 20:25:17 +0000 [info]: #0 starting fluentd worker pid=16 ppid=6 worker=0
2019-07-24 20:25:17 +0000 [info]: #0 fluentd worker is now running worker=0
2019-07-24 20:26:42 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-07-24 20:26:43 +0000 chunk="58e73200016262d0eca18b3796800408" error_class=SocketError error="Failed to open TCP connection to http-inputs-amway.splunkcloud.com:443 (getaddrinfo: Try again)"
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:1541:in `begin_transport'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:1493:in `transport_request'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/2.5.0/net/http.rb:1467:in `request'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:951:in `block in request'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:648:in `connection_for'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:945:in `request'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-splunk-hec-1.1.0/lib/fluent/plugin/out_splunk_hec.rb:355:in `send_to_hec'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-splunk-hec-1.1.0/lib/fluent/plugin/out_splunk_hec.rb:167:in `write'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-07-24 20:26:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'


Currently the metrics section of the values.yaml file is as follows:

splunk-kubernetes-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  kubernetes:
    insecureSSL: false (I tried both true and false)
    useRestClientSSL: true
    kubeletPort: 10250
  splunk:
    hec:
      indexName: index-metrics

Here is the configuration that logged when the container starts up:

2019-07-24 20:25:11 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics
    tag "kube.*"
    node_name "<Redacted>"
    kubelet_port 10250
    use_rest_client_ssl true
    cluster_name cluster_name
    interval 15s
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name cluster_name
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "http-inputs-<Redacted>.splunkcloud.com"
    hec_port 443
    hec_token "<Redacted>"
    host "<Redacted>"
    index "index-metrics"
    source "${tag}"
    insecure_ssl false
    <buffer>
      @type "memory"
      chunk_limit_records 10000
      chunk_limit_size 100m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 3
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>


Is there something special that needs to be configured for a metric index as the other two envent type indexes run with no errors in the logs?


Thanks again,
Bob Wieberdink

**Comment by matthewmodestino** [comment]
Hey Bob, I still see http in your splunk cloud input.

Can you check the running configmap for that pod? 

Also can you share your entire values.yaml?

**Comment by BobWieberdink** [comment]
Here is the configmap for the pod:
Name:         k8-connect-splunk-kubernetes-metrics
Namespace:    <Redacted>
Labels:       app=splunk-kubernetes-metrics
              chart=splunk-kubernetes-metrics-1.2.0
              heritage=Tiller
              release=k8-connect
Annotations:  <none>

Data
====
fluent.conf:
----
# system wide configurations
<system>
  log_level info
</system>
<source>
  @type kubernetes_metrics
  tag kube.*
  node_name "#{ENV['NODE_NAME']}"
  kubelet_port 10250
  use_rest_client_ssl true
  cluster_name cluster_name
  interval 15s
</source>
<filter kube.**>
  @type record_modifier
  <record>
    metric_name ${tag}
    cluster_name cluster_name
  </record>
</filter>
<filter kube.node.**>
  @type record_modifier
  <record>
    source ${record['node']}
  </record>
</filter>
<filter kube.pod.**>
  @type record_modifier
  <record>
    source ${record['node']}/${record['pod-name']}
  </record>
</filter>
<filter kube.sys-container.**>
  @type record_modifier
  <record>
    source ${record['node']}/${record['pod-name']}/${record['name']}
  </record>
</filter>
<filter kube.container.**>
  @type record_modifier
  <record>
    source ${record['node']}/${record['pod-name']}/${record['container-name']}
  </record>
</filter>
<match kube.**>
  @type splunk_hec
  data_type metric
  metric_name_key metric_name
  metric_value_key value
  protocol https
  hec_host http-inputs-<Redacted>.splunkcloud.com
  hec_port 443
  hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
  host "#{ENV['NODE_NAME']}"
  index index-metrics
  source ${tag}
  insecure_ssl false
  <buffer>
    @type memory
    chunk_limit_records 10000
    chunk_limit_size 100m
    flush_interval 5s
    flush_thread_count 1
    overflow_action block
    retry_max_times 3
    total_limit_size 400m
  </buffer>
</match>


Here is the current values.yaml file we are using:

global:
  logLevel: info
  splunk:
    hec:
      protocol: https
      insecureSSL: false
      host: http-inputs-<Redacted>.splunkcloud.com
      token: <Redacted>
      port: 443
splunk-kubernetes-logging:
  journalLogPath: /run/log/journal
  splunk:
    hec:
      indexName: index-log
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: false
  objects:
    core:
      v1:
        - name: pods
          interval: 30s
        - name: namespaces
          interval: 30s
        - name: nodes
          interval: 30s
        - name: services
          interval: 30s
        - name: config_maps
          interval: 30s
        - name: persistent_volumes
          interval: 30s
        - name: service_accounts
          interval: 30s
        - name: persistent_volume_claims
          interval: 30s
        - name: resource_quotas
          interval: 30s
        - name: component_statuses
          interval: 30s
        - name: events
          mode: watch
    apps:
      v1:
        - name: deployments
          interval: 30s
        - name: daemon_sets
          interval: 30s
        - name: replica_sets
          interval: 30s
        - name: stateful_sets
          interval: 30s
  splunk:
    hec:
      indexName: index-objects
splunk-kubernetes-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  kubernetes:
    insecureSSL: false
    useRestClientSSL: true
    kubeletPort: 10250
  splunk:
    hec:
      indexName: index-metrics

Thank you,

Bob Wieberdink

**Comment by matthewmodestino** [comment]
```
global:
logLevel: info
splunk:
hec:
protocol: https
insecureSSL: false
host: http-inputs-.splunkcloud.com
token: 
port: 443
```

try it like this:

```
global:
logLevel: info
splunk:
hec:
protocol: https
insecureSSL: false
host: https-inputs-myStackName.splunkcloud.com
token: 
port: 443

**Comment by matthewmodestino** [comment]
any luck Bob?

**Comment by BobWieberdink** [comment]
Interestingly enough, the issue, so far, seems to be environment related. I replaced HEC Host DNS with one of the IPs in the DNS record and I don't see the issue anymore. I am now working to recreate in one of our other K8 environments to see if the issue happens in the new environment.
