### ISSUE TITLE
Custom Resource Definition (CRD) Object Monitoring

### ISSUE THREAD

**Issue by ekristen** [splunk/splunk-connect-for-kubernetes#353]
Is it possible to monitor CRDs with the object monitoring? From the configuration it seems possible, but it errors when trying to monitor custom resource definitions. 

Error undefined method `watch_<replace_with_crd_name>`

**Comment by matthewmodestino** [comment]
I am not sure if the ruby client support it, but try:

custom_resource_definition as the object to watch. 

It wouldnt be the name of your crd...

https://github.com/splunk/splunk-connect-for-kubernetes/blob/20e67c6f2dcf4d06f6efc7cc6763126946a6956f/manifests/splunk-kubernetes-objects/configMap.yaml#L10

Try something like:

```
  <watch>
     resource_name custom_resource_definition
   </watch>
```

It is here you are trying to scrape in the objects configmap:

API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition

**Comment by ekristen** [comment]
I'll have to take a closer look at the ruby code then.  Perhaps what you are suggesting would work for monitoring actual CustomResourceDefinition definition objects, but I'm looking to monitor instances of a CRD. 

Like for example the Prometheus Operator has a CRD called Prometheus, it has it's own APIVersion and Kind type, I want to monitor it. 

When I tried modifying the helm chart to manually add the version and the kind like the docs suggest you can with the built in types it just threw the above error `watch_prometheus` undefined.

**Comment by matthewmodestino** [comment]
Ah, well technically the CRDs label things in such a way that you may be able to tell your story in the data we collect already. The watch would simply allow you to act to start the logic to triggering a monitor on something, but without doing any of that we will already see all its objects meta and logs and should be able to stich together with labels/dimensions

**Comment by ekristen** [comment]
After reviewing the code it seems like it should work. However I get errors about the thread creation bit that `watch_resource_name` isn't valid. I can seem to figure out why this would be.

**Comment by ekristen** [comment]
Ok upon further inspection, it doesn't work because the plugin is trying to use helper methods that do not exist on the default kubeclient gem for trying to get CRD information. 

IE it tries to do `get_nameofcrds` which is invalid on the `kubeclient` gem.

**Comment by matthewmodestino** [comment]
gotcha! 

Do you think we really need it or would the labels for the crd be enough?

**Comment by ekristen** [comment]
I guess it depends on the goals of the object monitoring?  I was looking at it from the perspective of using it to audit changes to the resources themselves.

Monitoring the core objects gets you only one piece of the picture.

**Comment by ekristen** [comment]
BTW I opened https://github.com/splunk/fluent-plugin-kubernetes-objects/issues/51 -- basically if it give it a CRD that it doesn't have helper methods for it essentially fork bombs the server running the object collection. It happens slowly, should be fixed regardless.

**Comment by matthewmodestino** [comment]
changes to the resources themselves can be done with kubernetes api audit logs. Thats what most projects I see use for this kinda thing. The objects pod is more meta enrichment.

**Comment by ekristen** [comment]
RE: Audit -- this might work, I'll take a deeper look into it. Thanks.

RE: Events -- Not all CRD end up creating Pods. There are many uses for CRDs. Events are only useful if the controller or something is monitoring the CRD and actually writing events for the changes, even then it's only as good as the information written into the event, it doesn't actually record the object properties only  that an object was involved.

**Comment by rosskusler** [comment]
Is there any prospect for getting CRDs supported in the kubernetes-objects pod? I would like to check for the existence of certain custom resource objects and can't rely on the apiserver audit logs because they objects don't change very frequently (hopefully).  I'm referring to the CRDs that get created by Gatekeeper when you defined ConstraintTemplates.

For instance I create a CRD called PolicyBannedVolumes in API group constraints.gatekeeper.sh/v1beta1 and put this into my config:
```
  <source>
    @type kubernetes_objects
    tag "kube.objects.*"
    api_version "constraints.gatekeeper.sh/v1beta1"
    insecure_ssl false
    <pull>
      resource_name "policy_banned_volumes"
      interval 60m
    </pull>
  </source>
```



That results in these logs.. some issue with the URL that it is generating:
```
2021-03-10 07:00:31 +0000 [info]: #0 starting fluentd worker pid=166 ppid=1 worker=0
2021-03-10 07:00:31 +0000 [info]: #0 fluentd worker is now running worker=0
2021-03-10 07:00:33 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::KubernetesObjectsInput title=:pull_policy_banned_volumes error_class=URI::InvalidURIError error="bad URI(is not URI?): https://10.96.0.1/apis/constraints.gatekeeper.sh/v1beta1/policybannedvolumes/{:namespace=>nil, :label_selector=>nil, :field_selector=>nil, :as=>:raw}"
#<Thread:0x0000559206b406c0@pull_policy_banned_volumes@/usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/usr/share/ruby/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://10.96.0.1/apis/constraints.gatekeeper.sh/v1beta1/policybannedvolumes/{:namespace=>nil, :label_selector=>nil, :field_selector=>nil, :as=>:raw} (URI::InvalidURIError)
	from /usr/share/ruby/uri/rfc3986_parser.rb:73:in `parse'
	from /usr/share/ruby/uri/common.rb:237:in `parse'
	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:606:in `parse_url_with_auth!'
	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:83:in `initialize'
	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `new'
	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'
	from /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:349:in `block in get_entity'
	from /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:121:in `handle_exception'
	from /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:347:in `get_entity'
	from /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:227:in `block (2 levels) in define_entity_methods'
	from /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:101:in `method_missing'
	from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.4/lib/fluent/plugin/in_kubernetes_objects.rb:203:in `public_send'
	from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.4/lib/fluent/plugin/in_kubernetes_objects.rb:203:in `block in create_pull_thread'
	from /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-03-10 07:00:33 +0000 [error]: #0 unexpected error error_class=URI::InvalidURIError error="bad URI(is not URI?): https://10.96.0.1/apis/constraints.gatekeeper.sh/v1beta1/policybannedvolumes/{:namespace=>nil, :label_selector=>nil, :field_selector=>nil, :as=>:raw}"
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/ruby/uri/rfc3986_parser.rb:67:in `split'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/ruby/uri/rfc3986_parser.rb:73:in `parse'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/ruby/uri/common.rb:237:in `parse'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:606:in `parse_url_with_auth!'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:83:in `initialize'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `new'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:349:in `block in get_entity'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:121:in `handle_exception'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:347:in `get_entity'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:227:in `block (2 levels) in define_entity_methods'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:101:in `method_missing'
  2021-03-10 07:00:33 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.4/lib/fluent/plugin/in_kubernetes_objects.rb:203:in `public_send'
  2021-03-10 07:00:33 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.4/lib/fluent/plugin/in_kubernetes_objects.rb:203:in `block in create_pull_thread'
  2021-03-10 07:00:33 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-03-10 07:00:33 +0000 [error]: #0 unexpected error error_class=URI::InvalidURIError error="bad URI(is not URI?): https://10.96.0.1/apis/constraints.gatekeeper.sh/v1beta1/policybannedvolumes/{:namespace=>nil, :label_selector=>nil, :field_selector=>nil, :as=>:raw}"
  2021-03-10 07:00:33 +0000 [error]: #0 suppressed same stacktrace
2021-03-10 07:00:33 +0000 [info]: Worker 0 finished unexpectedly with status 1
```
