### ISSUE TITLE
 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass> 

### ISSUE THREAD

**Issue by BrandonTsai** [splunk/splunk-connect-for-kubernetes#354]
**What happened**:
I found some error logs in splunk-kubernetes-metrics-agg pod

 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass> 

what does the error log mean?
How do I fix it?

**What you expected to happen**:
No Error logs 

**How to reproduce it (as minimally and precisely as possible)**:
Deploy to openshift by HELM

**Anything else we need to know?**:

configmap splunk-kubernetes-metrics-aggregator :
```yaml
apiVersion: v1
data:
  fluent.conf: |
    # system wide configurations
    <system>
      log_level debug
    </system>
    <source>
      @type kubernetes_metrics_aggregator
      tag kube.*
      interval 15s
    </source>
    <filter kube.**>
      @type record_modifier
      <record>
        metric_name ${tag}
        cluster_name openshift_sg_test
      </record>
    </filter>
    <filter kube.cluster.**>
      @type record_modifier
      <record>
        source ${record['name']}
      </record>
    </filter>
    <filter kube.namespace.**>
      @type record_modifier
      <record>
        source ${record['name']}
      </record>
    </filter>
    <filter kube.node.**>
      @type record_modifier
      <record>
        source ${record['node']}
      </record>
    </filter>
    <filter kube.pod.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}
      </record>
    </filter>
    <filter kube.sys-container.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}/${record['name']}
      </record>
    </filter>
    <filter kube.container.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}/${record['container-name']}
      </record>
    </filter>
    <match kube.**>
      @type splunk_hec
      data_type metric
      metric_name_key metric_name
      metric_value_key value
      protocol http
      hec_host "splunk.local"
      hec_port 8088
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['NODE_NAME']}"
      source source
      insecure_ssl false
      <buffer>
        @type memory
        chunk_limit_records 10000
        chunk_limit_size 8m
        flush_at_shutdown true
        flush_interval 3s
        flush_thread_burst_interval 0.01
        flush_thread_count 10
        flush_thread_interval 0.1
        overflow_action block
        retry_forever true
        retry_wait 60
        total_limit_size 4000m
      </buffer>
    </match>
kind: ConfigMap
metadata:
  creationTimestamp: "2019-09-26T05:06:38Z"
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.4.0
    heritage: Tiller
    release: splunk-kubernetes-metrics
  name: splunk-kubernetes-metrics-aggregator
  namespace: splunk-connect
  resourceVersion: "74534739"
  selfLink: /api/v1/namespaces/splunk-connect/configmaps/splunk-kubernetes-metrics-aggregator
  uid: 6b7e71eb-e01b-11e9-a34b-0050569e165d
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```bash
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-12-24T05:49:02Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-12-24T05:49:02Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```
- Splunk version:

Splunk Enterprise
Version:
7.2.3
Build:
06d57c595b80

- Others:

**Comment by matthewmodestino** [comment]
Hey! I have seen this before, but its escaping me what config tweak resolves it. How are you deploying and what version of our charts?

I feel like it had to do with the node name that was resolved.

**Comment by BrandonTsai** [comment]
Hi @matthewmodestino,

We deploy splunk-connect-for-k8s version 1.4.0 to openshift by helm.

**Comment by matthewmodestino** [comment]
Can we see the `values.yaml` ? Did you set the openshift flag? 

The “agg” pod scrapes the k8s api, i recall seeing this, an i’msure theres a closed issue in the repo on it...just cant seem to find it.

**Comment by matthewmodestino** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-connect-for-kubernetes/values.yaml

**Comment by matthewmodestino** [comment]
any luck?

**Comment by matthewmodestino** [comment]
@chaitanyaphalak can you confirm if this is similar to when we used to see it here?

https://github.com/splunk/splunk-connect-for-kubernetes/issues/157#issuecomment-523557880

**Comment by matthewmodestino** [comment]
```$ oc get deployments sck-rendered-splunk-kubernetes-metrics-agg -o jsonpath="{ .spec.template.spec.containers[0].image }"
docker.io/splunk/k8s-metrics-aggr:1.1.2```

```
$ oc version                                                                                                             
Client Version: v4.2.21
Server Version: 4.2.14
Kubernetes Version: v1.14.6+b294fe5
```

**Comment by BrandonTsai** [comment]
The NODE_NAME resolution is fine.

It looks similar to #157 , but this issue still exist in the latest splunk/k8s-metrics-aggr:1.1.2 and splunk/k8s-metrics:1.1.3 images
I will try to build the image from the latest develop branch as suggested in #157

**Comment by BrandonTsai** [comment]
After some investigation, I believe it is related [https://github.com/splunk/fluent-plugin-k8s-metrics-agg/issues/31](https://github.com/splunk/fluent-plugin-k8s-metrics-agg/issues/31)

**Comment by jayntguru** [comment]
We're receiving the same error and not using OpenShift. This is on Rancher running a managed cluster (not on the RKE).

2020-05-08 17:05:29 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass>
2020-05-08 17:05:29 +0000 [error]: #0 suppressed same stacktrace

**Comment by druesendieb** [comment]
We're running the SKC helm chart 1.4.1(non OpenShift) with metrics-aggr 1.1.2 on Rancher and are facing the same problem.

The complete event log of the fresh metrics-agg pod from today:
```
`/opt/app-root/src` is not writable.
Bundler will use `/tmp/bundler20200724-1-19qs2t1' as your home directory temporarily.
fatal: not a git repository (or any of the parent directories): .git
2020-07-24 12:57:01 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-07-24 12:57:01 +0000 [info]: gem 'fluentd' version '1.9.1'
2020-07-24 12:57:01 +0000 [info]: gem 'fluent-plugin-k8s-metrics-agg' version '1.1.2'
2020-07-24 12:57:01 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.4.2'
2020-07-24 12:57:01 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2020-07-24 12:57:01 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-07-24 12:57:01 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.1'
2020-07-24 12:57:04 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics_aggregator
    tag "kube.*"
    interval 15s
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name cluster_name
    </record>
  </filter>
  <filter kube.cluster.**>
    @type record_modifier
    <record>
      source ${record['name']}
    </record>
  </filter>
  <filter kube.namespace.**>
    @type record_modifier
    <record>
      source ${record['name']}
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host ""
    hec_port 8088
    hec_token ""
    host ""
    index "em_metrics"
    source "source"
    <buffer>
      @type "memory"
      chunk_limit_records 10000
      chunk_limit_size 100m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 3
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>
2020-07-24 12:57:04 +0000 [info]: starting fluentd-1.9.1 pid=1 ruby="2.5.5"
2020-07-24 12:57:04 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "-r/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/setup", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "--under-supervisor"]
fatal: not a git repository (or any of the parent directories): .git
2020-07-24 12:57:07 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2020-07-24 12:57:07 +0000 [info]: adding filter pattern="kube.cluster.**" type="record_modifier"
2020-07-24 12:57:07 +0000 [info]: adding filter pattern="kube.namespace.**" type="record_modifier"
2020-07-24 12:57:07 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2020-07-24 12:57:07 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2020-07-24 12:57:07 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2020-07-24 12:57:07 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2020-07-24 12:57:07 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2020-07-24 12:57:08 +0000 [info]: adding source type="kubernetes_metrics_aggregator"
2020-07-24 12:57:09 +0000 [info]: #0 starting fluentd worker pid=11 ppid=1 worker=0
2020-07-24 12:57:09 +0000 [info]: #0 fluentd worker is now running worker=0
2020-07-24 12:57:25 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass>
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:578:in `block (3 levels) in process_resource_usage_res'
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:577:in `each'
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:577:in `block (2 levels) in process_resource_usage_res'
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:566:in `each'
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:566:in `block in process_resource_usage_res'
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:565:in `synchronize'
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:565:in `process_resource_usage_res'
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:554:in `handle_resource_usage_response'
  2020-07-24 12:57:25 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.2/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:543:in `scrape_resource_usage_metrics'
  2020-07-24 12:57:25 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-07-24 12:57:25 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-07-24 12:57:25 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-07-24 12:57:25 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-07-24 12:57:25 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-07-24 13:01:25 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass>
(...)
2020-07-24 16:00:10 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass>
  2020-07-24 16:00:10 +0000 [error]: #0 suppressed same stacktrace
```


A thing which got my attention is the following line:
`fatal: not a git repository (or any of the parent directories): .git`

**Comment by druesendieb** [comment]
Problem is still persistent with SCK 1.4.2.

```
`/opt/app-root/src` is not writable.
Bundler will use `/tmp/bundler20200729-1-1u75p9o1' as your home directory temporarily.
fatal: not a git repository (or any of the parent directories): .git
2020-07-29 09:14:47 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-07-29 09:14:47 +0000 [info]: gem 'fluentd' version '1.9.1'
2020-07-29 09:14:47 +0000 [info]: gem 'fluent-plugin-k8s-metrics-agg' version '1.1.3'
2020-07-29 09:14:47 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2020-07-29 09:14:47 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-07-29 09:14:47 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.3'
2020-07-29 09:14:49 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics_aggregator
    tag "kube.*"
    interval 15s
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name cluster_name
    </record>
  </filter>
  <filter kube.cluster.**>
    @type record_modifier
    <record>
      source ${record['name']}
    </record>
  </filter>
  <filter kube.namespace.**>
    @type record_modifier
    <record>
      source ${record['name']}
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "host.internal.eu"
    hec_port 8088
    hec_token "Token"
    host ""
    index "em_metrics"
    source "source"
    insecure_ssl true
    <buffer>
      @type "memory"
      chunk_limit_records 10000
      chunk_limit_size 10m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 5
      retry_type periodic
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>
2020-07-29 09:14:49 +0000 [info]: starting fluentd-1.9.1 pid=1 ruby="2.5.5"
2020-07-29 09:14:49 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "-r/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/setup", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "--under-supervisor"]
fatal: not a git repository (or any of the parent directories): .git
2020-07-29 09:14:52 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2020-07-29 09:14:52 +0000 [info]: adding filter pattern="kube.cluster.**" type="record_modifier"
2020-07-29 09:14:52 +0000 [info]: adding filter pattern="kube.namespace.**" type="record_modifier"
2020-07-29 09:14:52 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2020-07-29 09:14:52 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2020-07-29 09:14:53 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2020-07-29 09:14:53 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2020-07-29 09:14:53 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2020-07-29 09:14:53 +0000 [info]: adding source type="kubernetes_metrics_aggregator"
2020-07-29 09:14:54 +0000 [info]: #0 starting fluentd worker pid=11 ppid=1 worker=0
2020-07-29 09:14:54 +0000 [info]: #0 fluentd worker is now running worker=0
2020-07-29 09:15:11 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass>
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:578:in `block (3 levels) in process_resource_usage_res'
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:577:in `each'
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:577:in `block (2 levels) in process_resource_usage_res'
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:566:in `each'
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:566:in `block in process_resource_usage_res'
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:565:in `synchronize'
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:565:in `process_resource_usage_res'
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:554:in `handle_resource_usage_response'
  2020-07-29 09:15:11 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.3/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:543:in `scrape_resource_usage_metrics'
  2020-07-29 09:15:11 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-07-29 09:15:11 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-07-29 09:15:11 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-07-29 09:15:11 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-07-29 09:15:11 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-07-29 09:15:40 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass>
  2020-07-29 09:15:40 +0000 [error]: #0 suppressed same stacktrace
2020-07-29 09:15:55 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass>
  2020-07-29 09:15:55 +0000 [error]: #0 suppressed same stacktrace
2020-07-29 09:16:10 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `/' for nil:NilClass>
  2020-07-29 09:16:10 +0000 [error]: #0 suppressed same stacktrace
```


Heres the metrics part of my `values.yaml`
```
splunk-kubernetes-metrics:
  enabled: true
  logLevel:
  rbac:
    create: true
  serviceAccount:
    create: true
    name:
    usePullSecrets: false
  splunk:
    hec:
      host:
      port:
      token:
      protocol:
      indexName: em_metrics
      insecureSSL:
      clientCert:
      clientKey:
      caFile:
  secret:
    create: true
    name:
  image:
    registry: docker.io
    name: splunk/k8s-metrics
    tag: 1.1.4
    pullPolicy: IfNotPresent
    usePullSecret: false
    pullsecretName:
  imageAgg:
    registry: docker.io
    name: splunk/k8s-metrics-aggr
    tag: 1.1.3
    pullPolicy: IfNotPresent
    usePullSecret: false
    pullsecretName:
  resources:
    fluent:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 300Mi
  buffer:
    "@type": memory
    total_limit_size: 400m
    chunk_limit_size: 10m
    chunk_limit_records: 10000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic
  aggregatorBuffer:
    "@type": memory
    total_limit_size: 400m
    chunk_limit_size: 10m
    chunk_limit_records: 10000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic
  metricsInterval: 15s
  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  aggregatorTolerations: {}
  priorityClassName:
  affinity: {}
  kubernetes:
    kubeletAddress:
    kubeletPort:
    kubeletPortAggregator:
    useRestClientSSL: true
    insecureSSL: true
    caFile:
    bearerTokenFile:
    secretDir:
    clusterName:
    openshift: false
    customFilters: {}
```

**Comment by druesendieb** [comment]
Hey @rockb1017,

the error slightly changed:
```
+0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `fetch' for nil:NilClass>
+0000 [error]: #0 suppressed same stacktrace
```

**Comment by SuitableProduce** [comment]
Is there any update on this?

**Comment by rockb1017** [comment]
Hello, Sorry for late reply. 

it is a known issue for metrics with Rancher. 
Anyways, i have added handling NilClass and created image `rock1017/k8s-metrics-aggr:1.1.5rc2` 
would you be able to run it with this image and see if problem is gone? 
this image is just for testing purpose only.
