### ISSUE TITLE
How do you enable SSL connections to the indexer?

### ISSUE THREAD

**Issue by dmcnaught** [splunk/splunk-connect-for-kubernetes#38]
I've looked at the helm docs, but I don't see any instructions on where to specify the certs to connect to the indexer after setting `insecureSSL: false` in the helm values.yml

```
2018-10-10 22:12:48 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-10-10 22:12:48 +0000 chunk="577e7273b2f87eac439ed0708b15ea3c" error_class=OpenSSL::SSL::SSLError error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)"
```

**Comment by dmcnaught** [comment]
ok - I've found them: https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-kubernetes-logging/values.yaml

**Comment by dmcnaught** [comment]
I'm currently getting this error when I think I've configured the certs correctly:
```
#0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="Private key is needed.
```

**Comment by dmcnaught** [comment]
@matthewmodestino thanks for your reply.
How did you set/get the variables for the splunk-connect-for-kubernetes (clientCert clientKey caFile) from the files you have on your server?

**Comment by matthewmodestino** [comment]
I didn't as I did not require checking of the client. Are you trying to ensure HEC side check the client cert?

**Comment by matthewmodestino** [comment]
Right, you do not need the certs in the splunk-connect-for-kubernetes config to send data over ssl, but you do need a trusted cert on the HEC endpoint to send with ```insecureSSL: false```. 

So on your HEC endpoint you should be able to use the same certs you put on your indexers to secure the ```s2s``` connection.

**Comment by dmcnaught** [comment]
Thanks for the help @matthewmodestino - I've got it all up and running well now.

**Comment by hhagewood** [comment]
Our kubernetes is running as AKS in Azure.
We are getting this same error on our Metrics pods that are running after the deploy :  ...error="SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (self signed certificate in certificate chain)"

For the logger and object pods we are getting a different error in the logs:  ..error="Failed to open TCP connection to https:443 (getaddrinfo: Name or service not known)"

Our HEC is deployed and active on our SplunkCloud managed search heads.  I can post JSON test events and metrics all day long to that HEC endpoint using Postman but the Splunk Connect for Kubernetes just doesn't connect.

**Comment by dmcnaught** [comment]
@hhagewood do you have 
````
global:
  splunk:
    hec:
      insecureSSL: false
```
and do you have `clientCert` `clientKey` or `caFile` set?
If so - try setting `insecureSSL: false` and removing the other 3 settings.
I was confusing setting up a universal forwarder with setting up splunk-connect-for-kubernetes

**Comment by rufengxu** [comment]
> @hhagewood do you have
> 
> ```
> global:
>   splunk:
>     hec:
>       insecureSSL: false
> ```
> 
> and do you have `clientCert` `clientKey` or `caFile` set?
> If so - try setting `insecureSSL: false` and removing the other 3 settings.
> I was confusing setting up a universal forwarder with setting up splunk-connect-for-kubernetes

I am using the manifest file directly.
Could you please give me an example what the syntax looks like in the configmap.yaml.  I have the cacert file and manual curl works if I add --cacert=, but I do not know what the syntax looks like in the configmap.yaml. Thanks.

**Comment by matthewmodestino** [comment]
hey @rufengxu!

in your `values.yaml` you will set `insecureSSL: false` to tell the plugin to validate the HEC server cert, which will then use the actual cert set in `caFile`. If you dont set one I believe we use mozilla `ca-certiricate` ruby package.


https://github.com/splunk/splunk-connect-for-kubernetes/blob/75dce82df9aa1149b5a1b9921658f49b2cc5e7db/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L70


which will render here:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/75dce82df9aa1149b5a1b9921658f49b2cc5e7db/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L318

**Comment by devopsksr** [comment]
I have custom certs for splunk which is a  stand alone. i have 
ca.cer         fullchain.pem                     splunk.dev.online.io.conf      splunk.dev.online.io.key
cert.pem       key.pem                           splunk.dev.online.io.csr       
fullchain.cer  splunk.dev.online.io.cer  splunk.dev.online.io.csr.conf  

What values should be given in values.yml file for 
  clientCert:
  clientKey:
  caFile:

**Comment by matthewmodestino** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/blob/53d5b0c1e333ad04c16a556aedd137f15c95a630/helm-chart/splunk-connect-for-kubernetes/values.yaml#L25

^ see spec for settings here

**Comment by devopsksr** [comment]
I have to configure a secure connection to splunk so that i have custom certs(lets encrypt)  installed in splunk stanalone instance in aws. i have my values.yml which has insecure: false as below
      insecureSSL: false
      clientCert: /root/certificates/splunkcer.pem
      clientKey: /root/certificates/splunkKeyFileInPemFormat.pem
      caFile: /root/certificates/ca.pem

When i run the helm chart it in splunk-kubernetes-logging-5x8cr log shows as below its same with all pods. Could you please what is that i am missing.

2020-09-02 13:21:57 +0000 [info]: #0 starting fluentd worker pid=6943 ppid=1 worker=0
2020-09-02 13:21:57 +0000 [error]: #0 unexpected error error_class=OpenSSL::X509::CertificateError error="not enough data"
  2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:132:in `initialize'
  2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:132:in `new'
  2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:132:in `block in start'
  2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:130:in `tap'
  2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:130:in `start'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:200:in `block in start'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:179:in `block (2 levels) in lifecycle'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:121:in `block (2 levels) in lifecycle'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:120:in `each'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:120:in `block in lifecycle'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:113:in `each'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:113:in `lifecycle'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:178:in `block in lifecycle'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:175:in `each'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:175:in `lifecycle'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:199:in `start'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/engine.rb:248:in `start'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/engine.rb:147:in `run'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:590:in `block in run_worker'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:825:in `main_process'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:584:in `run_worker'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/command/fluentd.rb:338:in `<top (required)>'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/bin/fluentd:8:in `require'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/bin/fluentd:8:in `<top (required)>'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2020-09-02 13:21:57 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
2020-09-02 13:21:57 +0000 [error]: #0 unexpected error error_class=OpenSSL::X509::CertificateError error="not enough data"
  2020-09-02 13:21:57 +0000 [error]: #0 suppressed same stacktrace

**Comment by devopsksr** [comment]
I am successfully able to configure splunk with OCP using insecure: true Now I have to configure a secure connection to splunk for that i have custom certs(lets encrypt) installed in splunk stanalone instance in aws. i have my values.yml which has insecure: false as below
insecureSSL: false
clientCert: /root/certificates/splunkcer.pem
clientKey: /root/certificates/splunkKeyFileInPemFormat.pem
caFile: /root/certificates/ca.pem

When i run the helm chart it in splunk-kubernetes-logging-5x8cr log shows as below, its same with all pods and i am not able to get any logs to splunk. Could you please let me know what is that i am missing.

2020-09-02 13:21:57 +0000 [info]: #0 starting fluentd worker pid=6943 ppid=1 worker=0
2020-09-02 13:21:57 +0000 [error]: #0 unexpected error error_class=OpenSSL::X509::CertificateError error="not enough data"
2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:132:in initialize' 2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:132:in new'
2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:132:in block in start' 2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:130:in tap'
2020-09-02 13:21:57 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.2/lib/fluent/plugin/out_splunk_hec.rb:130:in start' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/compat/call_super_mixin.rb:42:in start'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:200:in block in start' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:179:in block (2 levels) in lifecycle'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:121:in block (2 levels) in lifecycle' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:120:in each'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:120:in block in lifecycle' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:113:in each'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/agent.rb:113:in lifecycle' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:178:in block in lifecycle'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:175:in each' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:175:in lifecycle'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:199:in start' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/engine.rb:248:in start'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/engine.rb:147:in run' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:590:in block in run_worker'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:825:in main_process' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:584:in run_worker'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/command/fluentd.rb:338:in <top (required)>' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/bin/fluentd:8:in require'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/bin/fluentd:8:in <top (required)>' 2020-09-02 13:21:57 +0000 [error]: #0 /usr/bin/fluentd:23:in load'
2020-09-02 13:21:57 +0000 [error]: #0 /usr/bin/fluentd:23:in `

'
2020-09-02 13:21:57 +0000 [error]: #0 unexpected error error_class=OpenSSL::X509::CertificateError error="not enough data"
2020-09-02 13:21:57 +0000 [error]: #0 suppressed same stacktrace

**Comment by orona-yuca** [comment]
Thanks @matthewmodestino for the explanations,

I'm already stuck on the configuration related to the `splunk.hec`, more specific about the 3 fields `clientCert`, `clientKey` and `caFile`. If get it right, I can create a certificate for Splunk, and when I do that I'll have the two first fields correct? After that how can I get the `caFile`?

Another doubt that I have is: at the `values.yaml` it requests the content of the certificate and the key, so I need to copy and paste the content of the .pem files directly to the yaml file?
