### ISSUE TITLE
Not able to logs metrics

### ISSUE THREAD

**Issue by dzlab** [splunk/splunk-connect-for-kubernetes#417]
**What happened**:
I'm trying to setup Splunk Connect for my k8s, I'm testing with a Docker Desktop. Logs and Objects are correctly reported by splunk connect but metrics are not.

**What you expected to happen**:
See metrics from my k8s logged into Splunk when searching with `index="k8s-metrics"`

**How to reproduce it (as minimally and precisely as possible)**:

```
$ helm install splunk-connect-daemonset -f metrics_values.yaml https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.1/splunk-connect-for-kubernetes-1.4.1.tgz 

$ cat metrics_values.yaml
global:
  logLevel: info
    hec:
      host: mysplunk.splunkcloud.com
      port: 8088
      token: MY_HEC_TOKEN
      protocol: https
      indexName: default
      insecureSSL: true

# local config for logging chart
splunk-kubernetes-logging:
  journalLogPath: /run/log/journal
  splunk:
    hec:
      indexName: k8s-logs

# local config for objects chart
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: true  
  objects:
    core:
      v1:
        - name: pods
        - name: namespaces
        - name: nodes
        - name: services
        - name: config_maps
        - name: secrets
        - name: persistent_volumes
        - name: service_accounts
        - name: persistent_volume_claims
        - name: resource_quotes
        - name: component_statuses
        - name: events
        - name: watch
    apps:
      v1:
        - name: deployments
        - name: daemon_sets 
        - name: replica_sets
        - name: stateful_sets
  splunk:
    hec:
      indexName: k8s-meta

# local config for metrics chart
splunk-kubernetes-metrics:
  splunk:
    hec:
      indexName: k8s-metrics
```

**Anything else we need to know?**:
All pods are running correctly
```
$ kubectl get pods
NAME                                                              READY   STATUS    RESTARTS   AGE
splunk-connect-daemonset-splunk-kubernetes-logging-7ltrg          1/1     Running   0          13m
splunk-connect-daemonset-splunk-kubernetes-metrics-agg-798t8tnz   1/1     Running   0          13m
splunk-connect-daemonset-splunk-kubernetes-metrics-qmxqs          1/1     Running   0          13m
splunk-connect-daemonset-splunk-kubernetes-objects-7c955f8rrsgw   1/1     Running   0          13m
```
But logs of the metrics daemonset are showing errors
```
$ kubectl logs splunk-connect-daemonset-splunk-kubernetes-metrics-qmxqs 
2020-06-29 22:30:17 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-06-29 22:30:17 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2020-06-29 22:30:17 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.4.2'
2020-06-29 22:30:17 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2020-06-29 22:30:17 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-06-29 22:30:17 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.1'
2020-06-29 22:30:17 +0000 [info]: gem 'fluentd' version '1.9.1'
2020-06-29 22:30:22 +0000 [info]: Use URL https://192.168.65.3:10250/stats/summary for creating client to query kubelet summary api
2020-06-29 22:30:22 +0000 [info]: Use URL https://192.168.65.3:10250/stats/ for creating client to query kubelet stats api
2020-06-29 22:30:22 +0000 [info]: Use URL https://192.168.65.3:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2020-06-29 22:30:22 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics
    tag "kube.*"
    node_name "docker-desktop"
    use_rest_client_ssl true
    cluster_name cluster_name
    interval 15s
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name cluster_name
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "mysplunk.splunkcloud.com"
    hec_port 8088
    hec_token "MY_HEC_TOKEN"
    host "docker-desktop"
    index "k8s-metrics"
    source "${tag}"
    insecure_ssl true
    <buffer>
      @type "memory"
      chunk_limit_records 10000
      chunk_limit_size 100m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 3
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>
2020-06-29 22:30:22 +0000 [info]: starting fluentd-1.9.1 pid=1 ruby="2.5.5"
2020-06-29 22:30:22 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-p", "/fluentd/plugins", "-c", "/fluentd/etc/fluent.conf", "--under-supervisor"]
2020-06-29 22:30:25 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2020-06-29 22:30:25 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2020-06-29 22:30:25 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2020-06-29 22:30:25 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2020-06-29 22:30:25 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2020-06-29 22:30:25 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2020-06-29 22:30:26 +0000 [info]: adding source type="kubernetes_metrics"
2020-06-29 22:30:29 +0000 [info]: #0 Use URL https://192.168.65.3:10250/stats/summary for creating client to query kubelet summary api
2020-06-29 22:30:29 +0000 [info]: #0 Use URL https://192.168.65.3:10250/stats/ for creating client to query kubelet stats api
2020-06-29 22:30:29 +0000 [info]: #0 Use URL https://192.168.65.3:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2020-06-29 22:30:29 +0000 [warn]: parameter 'cluster_name' in <source>
  @type kubernetes_metrics
  tag "kube.*"
  node_name "docker-desktop"
  use_rest_client_ssl true
  cluster_name cluster_name
  interval 15s
</source> is not used.
2020-06-29 22:30:29 +0000 [info]: #0 starting fluentd worker pid=10 ppid=1 worker=0
2020-06-29 22:30:29 +0000 [info]: #0 fluentd worker is now running worker=0
2020-06-29 22:30:44 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=RestClient::SSLCertificateNotVerified error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)"
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
  2020-06-29 22:30:44 +0000 [error]: #0 /fluentd/plugins/in_kubernetes_metrics.rb:635:in `scrape_metrics'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-06-29 22:30:44 +0000 [error]: #0 Timer detached. title=:metric_scraper
2020-06-29 22:30:44 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=RestClient::SSLCertificateNotVerified error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)"
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
  2020-06-29 22:30:44 +0000 [error]: #0 /fluentd/plugins/in_kubernetes_metrics.rb:647:in `scrape_stats_metrics'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-06-29 22:30:44 +0000 [error]: #0 Timer detached. title=:stats_metric_scraper
2020-06-29 22:30:44 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=RestClient::SSLCertificateNotVerified error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)"
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
  2020-06-29 22:30:44 +0000 [error]: #0 /fluentd/plugins/in_kubernetes_metrics.rb:660:in `scrape_cadvisor_metrics'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-06-29 22:30:44 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-06-29 22:30:44 +0000 [error]: #0 Timer detached. title=:cadvisor_metric_scraper
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): OSX Running Docker Desktip
- Splunk version: Splunk Cloud
- Others:

**Comment by chaitanyaphalak** [comment]
try setting insecureSSL for metrics charts

**Comment by dzlab** [comment]
I've tried with this setup
```
splunk-kubernetes-metrics:
  kubernetes:
    insecureSSL: true  
  splunk:
    hec:
      indexName: k8s-metrics
```

Now I don;t see any error in the logs, however looking at my Splunk Cloud account I see nothing when searching with `index="k8s-metrics"`

```
$ k logs splunk-connector-splunk-kubernetes-metrics-7rfph
2020-06-30 23:31:50 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-06-30 23:31:51 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2020-06-30 23:31:51 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.4.2'
2020-06-30 23:31:51 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2020-06-30 23:31:51 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-06-30 23:31:51 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.1'
2020-06-30 23:31:51 +0000 [info]: gem 'fluentd' version '1.9.1'
2020-06-30 23:31:55 +0000 [info]: Use URL https://192.168.65.3:10250/stats/summary for creating client to query kubelet summary api
2020-06-30 23:31:55 +0000 [info]: Use URL https://192.168.65.3:10250/stats/ for creating client to query kubelet stats api
2020-06-30 23:31:55 +0000 [info]: Use URL https://192.168.65.3:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2020-06-30 23:31:55 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics
    tag "kube.*"
    node_name "docker-desktop"
    use_rest_client_ssl true
    insecure_ssl true
    cluster_name cluster_name
    interval 15s
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name cluster_name
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "mysplunk.splunkcloud.com"
    hec_port 8088
    hec_token "MY_HEC_TOKEN"
    host "docker-desktop"
    index "k8s-metrics"
    source "${tag}"
    insecure_ssl true
    <buffer>
      @type "memory"
      chunk_limit_records 10000
      chunk_limit_size 100m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 3
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>
2020-06-30 23:31:55 +0000 [info]: starting fluentd-1.9.1 pid=1 ruby="2.5.5"
2020-06-30 23:31:55 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-p", "/fluentd/plugins", "-c", "/fluentd/etc/fluent.conf", "--under-supervisor"]
2020-06-30 23:31:57 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2020-06-30 23:31:57 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2020-06-30 23:31:57 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2020-06-30 23:31:57 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2020-06-30 23:31:57 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2020-06-30 23:31:57 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2020-06-30 23:31:58 +0000 [info]: adding source type="kubernetes_metrics"
2020-06-30 23:32:01 +0000 [info]: #0 Use URL https://192.168.65.3:10250/stats/summary for creating client to query kubelet summary api
2020-06-30 23:32:01 +0000 [info]: #0 Use URL https://192.168.65.3:10250/stats/ for creating client to query kubelet stats api
2020-06-30 23:32:01 +0000 [info]: #0 Use URL https://192.168.65.3:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2020-06-30 23:32:01 +0000 [warn]: parameter 'cluster_name' in <source>
  @type kubernetes_metrics
  tag "kube.*"
  node_name "docker-desktop"
  use_rest_client_ssl true
  insecure_ssl true
  cluster_name cluster_name
  interval 15s
</source> is not used.
2020-06-30 23:32:01 +0000 [info]: #0 starting fluentd worker pid=10 ppid=1 worker=0
2020-06-30 23:32:01 +0000 [info]: #0 fluentd worker is now running worker=0
```

**Comment by rchenzheng** [comment]
I'm having the same issue

**Comment by mwang2016** [comment]
@dzlab Are you using Managed Splunk Cloud or Splunk Enterprise and Self-service Splunk Cloud? If you are using Managed Splunk Cloud the HEC port should be 443 instead of 8088. You might also need to configure a proper Splunk host with prefix. Here is the documentation that shows you how to set up HEC 
[https://docs.splunk.com/Documentation/Splunk/latest/Data/UsetheHTTPEventCollector]
pay attention the bottom of the page

**Comment by dzlab** [comment]
@mwang2016 I was using a trial Splunk Cloud account (I think it is expired), I think I tried with the 443 port but later got it working with 8088. My actual problem is that I can see objects and logs in the Splunk dashboard (both indexes are populated with data), only the metrics index was not populated.

**Comment by rchenzheng** [comment]
> @mwang2016 I was using a trial Splunk Cloud account (I think it is expired), I think I tried with the 443 port but later got it working with 8088. My actual problem is that I can see objects and logs in the Splunk dashboard (both indexes are populated with data), only the metrics index was not populated.

My account isn't expired, yet I'm having the same issue https://github.com/splunk/splunk-connect-for-kubernetes/issues/424

**Comment by mwang2016** [comment]
@dzlab Did you create Splunk index as metrics type?

**Comment by dzlab** [comment]
I'm sure I did create all indexes, as I double checked many times before creating this issue. I will try to create another trial account, try to reproduce the issue and update this issue.

**Comment by rockb1017** [comment]
@dzlab how are you verifying there is no data for the metrics index on splunk?
If you are seeing logs and objects, there is no issue with HEC address and port configuration. 

the issue might be coming from docker desktop version of kubernetes. it is more tricky than normal and also that environment is not what we have tested and verified against. 

what i would do next is turning on debug log for metrics pod.

**Comment by dzlab** [comment]
@rockb1017 I search on splunk with something like `index="k8s-metrics"` or `index="k8s-metrics" cluster_name="docker_desktop"`

**Comment by rockb1017** [comment]
oh that is why. Please see this to search the metrics. 
https://docs.splunk.com/Documentation/Splunk/8.0.5/Metrics/Search

**Comment by dzlab** [comment]
lol I was searching metrics as they were logs, this must be the problem as I remember checking the logs of the pod logging metrics and everything looked working good (well after fixing some errors and getting the connector to work).

**Comment by rockb1017** [comment]
cool! i will close this issue.
