### ISSUE TITLE
Fluentd crashes when multiple path values were added in values.yaml

### ISSUE THREAD

**Issue by druesendieb** [splunk/splunk-connect-for-kubernetes#452]
**What happened**:
Fluentd crashes when multiple path values were added in values.yaml

```
bundler: failed to load command: fluentd (/usr/bin/fluentd)
Fluent::ConfigParseError: got incomplete JSON array configuration at source.containers.conf line 33,9
 32:   </parse>
 33: </source>
     ---------^

  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/basic_parser.rb:92:in `parse_error!'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/literal_parser.rb:279:in `scan_json'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/literal_parser.rb:71:in `parse_literal'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:130:in `parse_element'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:95:in `parse_element'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:168:in `block in eval_include'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:162:in `each'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:162:in `eval_include'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:145:in `parse_include'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:104:in `parse_element'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:43:in `parse!'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config/v1_parser.rb:33:in `parse'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config.rb:58:in `parse'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/config.rb:39:in `build'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:617:in `configure'
  /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/command/fluentd.rb:329:in `<top (required)>'
  /usr/share/gems/gems/fluentd-1.9.1/bin/fluentd:8:in `require'
  /usr/share/gems/gems/fluentd-1.9.1/bin/fluentd:8:in `<top (required)>'
  /usr/bin/fluentd:23:in `load'
  /usr/bin/fluentd:23:in `<top (required)>'

```

The line in  `source.containers.conf` now looks like this:
```
      path [/var/log/containers/*.log path2/*.log]
```
**What you expected to happen**:
The helm chart should handle the path values correctly and, if entered, create a correct a formatted JSON array for multiple path variables in the configmap.yaml for  `source.containers.conf: |-`

```
        path ["/var/log/containers/*.log","path2/*.log"]
```

**How to reproduce it (as minimally and precisely as possible)**:
Create a values.yaml containing something like this:

```
splunk-kubernetes-logging:
(...)
  fluentd:
    # path of logfiles, default /var/log/containers/*.log
    path: 
      - /var/log/containers/*.log
      - /path2/*.log
```
Apply the helm chart
Check the logs of the logging pods.

**Anything else we need to know?:**
Pull Request #451 already present.

**Environment**:
SCK 1.4.3

**Comment by mwang2016** [comment]
@druesendieb thank you, we will review your PR as soon as possible

**Comment by rockb1017** [comment]
for path, it should be comma separated string. please refer here.
closing.
