### ISSUE TITLE
failed to flush the buffer errors

### ISSUE THREAD

**Issue by brian-pratt** [splunk/splunk-connect-for-kubernetes#461]
For the Metrics pod it’s a lot of complaints about flushing the buffer and I can’t tell if the “retries succeeded” means it was able to flush, or the attempt to retry succeeded but it failed again. (grabbed with kubectl logs metrics-pod-name).  what do these errors mean??

2020-08-27 14:47:17 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-08-27 14:47:18 +0000 chunk="5addccb0cfb5a8c6c9528d8233d2b63f" error_class=Net::HTTP::Persistent::Error
error="too many connection resets (due to Connection timed out - Errno::ETIMEDOUT) after 0 requests on 46953262055540, last used 1598539637.4126399 seconds ago"
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/protocol.rb:233:in `write'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/protocol.rb:233:in `write0'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/protocol.rb:207:in `block in write'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/protocol.rb:224:in `writing'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/protocol.rb:206:in `write'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/http/generic_request.rb:188:in `send_request_with_body'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/http/generic_request.rb:121:in `exec'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/http.rb:1495:in `block in transport_request'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/http.rb:1494:in `catch'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/http.rb:1494:in `transport_request'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/net/http.rb:1467:in `request'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:964:in `block in request'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:662:in `connection_for'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/fluent-plugin-splunk-hec-1.2.1/lib/fluent/plugin/out_splunk_hec.rb:293:in `write_to_splunk'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/fluent-plugin-splunk-hec-1.2.1/lib/fluent/plugin/out_splunk.rb:97:in `block in write'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/ruby/benchmark.rb:308:in `realtime'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/fluent-plugin-splunk-hec-1.2.1/lib/fluent/plugin/out_splunk.rb:96:in `write'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/compat/output.rb:131:in `write'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-08-27 14:47:17 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-08-27 14:47:18 +0000 [warn]: #0 retry succeeded. chunk_id="5addccb0cfb5a8c6c9528d8233d2b63f"
2020-08-27 15:05:49 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-08-27 15:05:50 +0000 chunk="5addd0d365afcfeb9f3d39cdbba138eb" error_class=Net::HTTP::Persistent::Error
error="too many connection resets (due to Connection timed out - Errno::ETIMEDOUT) after 0 requests on 46953262055540, last used 1598540749.476127 seconds ago"
  2020-08-27 15:05:49 +0000 [warn]: #0 suppressed same stacktrace

Environment Info
PKS 1.7.1 running on NSX-T 2.5.1
No firewalls within Kubernetes at all, all of its external to NSX-T 
Kubernetes 1.16.2 (with some vmware bugs, hence the +vmware version I sent you in chat)
PodSecurityPolicies are in play, but I am using the ones provided by SC
This is all Bosh deployed stuff, I can’t add packages to VMs or change the VM’s at all.

**Comment by rockb1017** [comment]
from the log you attached, it seems it is successfully completing retry request. but it is odd that it complains a lot. This is not normal and there is something wrong in the connection between this pod and Splunk HEC endpoint. (network or etc.) 
1. Do you see metrics data getting ingested to Splunk?

2. Could you turn on the debug log and post what you get here?  

Thank you.

**Comment by brian-pratt** [comment]
Yes, we do see data getting into Splunk.  I'm going to close this issue because this is a lab environment and there known constraints on the HEC side.  I can see indexing queues filling to 100%.  We'll see if this comes up again when we move to an environment with better capacity to support the traffic we are sending.   thank you for the input.

**Comment by rockb1017** [comment]
i see. thank you!
