### ISSUE TITLE
failed to flush the buffer/error_class=RuntimeError error="Server error (503)

### ISSUE THREAD

**Issue by manekanttasuru** [splunk/splunk-connect-for-kubernetes#474]
Hii ,
I am trying to setup splunk connect for kubernetes-metrics for my EKS , i have deployed helm chart with my values file using https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics . i see all my daemonset pods in running state . i see chunks of data getting produced too. i was getting this below error in the logs of splunk pods 

Bundler will use `/tmp/bundler20200929-1-swnzdj1' as your home directory temporarily.
2020-09-29 17:44:25 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-09-29 17:44:25 +0000 [info]: gem 'fluentd' version '1.9.1'
2020-09-29 17:44:25 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2020-09-29 17:44:25 +0000 [info]: gem 'fluent-plugin-kubernetes-metrics' version '1.1.4'
2020-09-29 17:44:25 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2020-09-29 17:44:25 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-09-29 17:44:25 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.3'
2020-09-29 17:44:27 +0000 [info]: Use URL https://XXXXX:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2020-09-29 17:44:27 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics
    tag "kube.*"
    node_name "XXXXl"
    use_rest_client_ssl true
    insecure_ssl true
    cluster_name cluster_name
    interval 15s
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name cluster_name
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "XXXXXX"
    hec_port 443
    hec_token "MY HEC TOKEN"
    host "XXXXXl"
    index "XXXX"
    source "${tag}"
    insecure_ssl true
    <buffer>
      @type "memory"
      path /var/log/fluentd-buffers/kubernetes.system.buffer
      chunk_limit_records 10000
      chunk_limit_size 20m
      flush_interval 10s
      flush_thread_count 5
      overflow_action block
      retry_max_times 3
      total_limit_size 100m
    </buffer>
  </match>
</ROOT>
2020-09-29 17:44:31 +0000 [info]: #0 starting fluentd worker pid=9 ppid=1 worker=0
2020-09-29 17:44:31 +0000 [info]: #0 fluentd worker is now running worker=0
2020-09-29 18:25:20 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-29 18:25:21 +0000 chunk="XXXXXXXXXXX" error_class=RuntimeError error="Server error (503) for POST https://XXXXXX/services/collector, response: {\"text\":\"Server is busy\",\"code\":9,\"invalid-event-number\":2}"
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/gems/gems/fluent-plugin-splunk-hec-1.2.3/lib/fluent/plugin/out_splunk_hec.rb:306:in `write_to_splunk'
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/gems/gems/fluent-plugin-splunk-hec-1.2.3/lib/fluent/plugin/out_splunk.rb:97:in `block in write'
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/ruby/benchmark.rb:308:in `realtime'
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/gems/gems/fluent-plugin-splunk-hec-1.2.3/lib/fluent/plugin/out_splunk.rb:96:in `write'
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/compat/output.rb:131:in `write'
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-09-29 18:25:20 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-09-29 18:25:21 +0000 [warn]: #0 retry succeeded. chunk_id="XXXXXXXXXXXXXXXX"
2020-09-29 19:53:54 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-29 19:53:55 +0000 chunk="XXXXXXXXXXXXXXX" error_class=RuntimeError error="Server error (503) for POST https://10.202.72.252/services/collector, response: {\"text\":\"Server is busy\",\"code\":9,\"invalid-event-number\":0}"
2020-09-29 23:18:48 +0000 [warn]: #0 retry succeeded. chunk_id="XXXXXXX"
2020-09-29 23:20:26 +0000 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=29.56220881268382 slow_flush_log_threshold=20.0 plugin_id="object:2b13c89a15e4"
2020-09-29 23:23:14 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-29 23:23:15 +0000 chunk="XXXXXXXXXf" error_class=RuntimeError error="Server error (504) for POST https://XXXXX/services/collector, response: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>Apple</center>\r\n</body>\r\n</html>\r\n"
2020-09-30 04:05:11 +0000 [info]: #0 fluentd worker is now stopping worker=0
2020-09-30 04:05:11 +0000 [info]: #0 shutting down fluentd worker worker=0
2020-09-30 04:05:11 +0000 [info]: #0 shutting down input plugin type=:kubernetes_metrics plugin_id="object:2b13c8daa910"
2020-09-30 04:05:12 +0000 [info]: #0 shutting down output plugin type=:splunk_hec plugin_id="object:2b13c89a15e4"
2020-09-30 04:05:12 +0000 [info]: #0 shutting down filter plugin type=:record_modifier plugin_id="object:2b13c7e69960"
2020-09-30 04:05:12 +0000 [info]: #0 shutting down filter plugin type=:record_modifier plugin_id="object:2b13c7ee5df8"
2020-09-30 04:05:12 +0000 [info]: #0 shutting down filter plugin type=:record_modifier plugin_id="object:2b13c7f2a7f0"
2020-09-30 04:05:12 +0000 [info]: #0 shutting down filter plugin type=:record_modifier plugin_id="object:2b13c7fb9af4"
2020-09-30 04:05:12 +0000 [info]: #0 shutting down filter plugin type=:record_modifier plugin_id="object:2b13c889de68"
2020-09-30 04:05:12 +0000 [info]: Worker 0 finished with status 0

FYI : i was able to curl and send my metrics from the pod and node and my local station . I was able to access and load the data in splunk frequently .

Apart from this can someone help me with these questions too please 
1. can we use the same index for metrics, logs and objects ?
2. i need to send my cpu and memory metrics to my splunk index with the help of HEC and create alerts . Any suggestions ?
3. Like wise docker inspect , how can i inspect my chunk data ?
4. Is it possible to curl and send chunk data manually from pod/node ?
5. where can i see the list of chunks being populated on my worker node ?

Thanks in advance

**Comment by chaitanyaphalak** [comment]
hey @manekanttasuru are you forwarding data to a metrics index. Also from 503 errors and hec code 9 it looks like HEC is overwhelmed - https://docs.splunk.com/Documentation/Splunk/8.0.6/Data/TroubleshootHTTPEventCollector#Possible_error_codes

**Comment by manekanttasuru** [comment]
thanks for the reply **chaitanyaphalak**  , yes i am forwarding data to a metrics index , i see few of the chunks in the splunk index today , and few of the chunks with  502, 503 AND 504. This is too strange to me  

2020-09-30 23:35:56 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-30 23:35:57 +0000 chunk="XXXXXXX" error_class=RuntimeError error="Server error (503) for POST https://XXXXXX/services/collector, response: {\"text\":\"Server is busy\",\"code\":9,\"invalid-event-number\":0}"

2020-10-01 00:30:19 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-10-01 00:30:20 +0000 chunk="XXXXXXXX" error_class=RuntimeError error="Server error (502) for POST https://XXXXX/services/collector, response: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center></center>\r\n</body>\r\n</html>

2020-09-30 23:14:24 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-30 23:14:25 +0000 chunk="XXXXXXXXX" error_class=RuntimeError error="Server error (504) for POST https://XXXXX/services/collector, response: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center></center>\r\n</body>\r\n</html>

How can i fix these and can you help me by answering my questions too please . Thanks in advance

**Comment by matthewmodestino** [comment]
Hi can you please tell us more about the Splunk environment? 

The errors above seem to be cause by the network and or the Splunk instance you are sending to needing some tuning/scaling...

How many nodes/pods are in this EKS cluster, and how is the Splunk environment set up?
