### ISSUE TITLE
metrics are stopped and not restarting when kubelet is not reachable

### ISSUE THREAD

**Issue by schose** [splunk/splunk-connect-for-kubernetes#493]
**What happened**:

We are closely monitoring if metrics from clusters are ingested into splunk enterprise. using following search:

```
`k8s_objects` sourcetype="kube:objects:nodes" earliest=-15m@m | stats values(metadata.name) as nodename by cluster_name | mvexpand nodename
| join type=left nodename
[
  | mstats count as metriccount WHERE metric_name="kube.node.cpu.usage" `k8s_metrics` earliest=-15m@m latest=-0m@m by node
  | rename node as nodename
]
| fillnull value=0
| search metriccount=0
```

We see that sometimes metrics are not send anymore. Root-cause seems to be that kubelet is not responding for any reason. The metric container shows errors like:

```
"2020-10-24 08:08:26 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=RestClient::Unauthorized error="401 Unauthorized"
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/ruby/net/http.rb:910:in `start'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
  2020-10-24 08:08:26 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-kubernetes-metrics-1.1.4/lib/fluent/plugin/in_kubernetes_metrics.rb:660:in `scrape_cadvisor_metrics'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-10-24 08:08:26 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-10-24 08:08:26 +0000 [error]: #0 Timer detached. title=:cadvisor_metric_scraper%
```
same happens if kubelet is stopped for a while:

```
2020-11-05 16:15:14 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=Errno::ECONNREFUSED error="Failed to open TCP connection to 192.168.53.112:10250 (Connection refused - connect(2) for \"192.168.53.112\" port 10250)"
...
2020-11-05 16:15:14 +0000 [error]: #0 Timer detached. title=:cadvisor_metric_scraper
```
container is not restarted, as there is no liveness check defined and processes are still running in container while error occurs.

```
k exec my-splunk-connect-splunk-kubernetes-metrics-h9q96 ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ssl    0:02 /usr/bin/fluentd -c /fluentd/etc/fluent.conf
    9 ?        Sl     0:08 /usr/bin/ruby -Eascii-8bit:ascii-8bit -r/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/setup /usr/bin/fluentd -c /fluentd/etc/fluent.conf --under-supervisor
  162 pts/0    Ss+    0:00 /bin/bash
  168 ?        Rs     0:00 ps ax
```

**What you expected to happen**:

metrics scraping is restarted when kublet is available again.

**How to reproduce it (as minimally and precisely as possible)**:

0. install sck
1. stop kubelet for some some seconds
2. start kubelet
3. see errors in logs metrics are not delivered anymore

**Anything else we need to know?**:

reproduceable in openshift and k8s. 

**Environment**:
- Kubernetes version (use `kubectl version`): kubernetes v1.18.9 and openshift v4.5.13
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04 and coreos 4.5
- Splunk version: 8.0.5.1
- Splunk Connect for Kubernetes helm chart version: v1.4.3
- Others:

**Comment by schose** [comment]
I added a liveness probe in my [fork](https://github.com/schose/splunk-connect-for-kubernetes/blob/904a869e536730531fa51e9f2ce5accc200cb4bf/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml#L52) which i adjusted from here   [fluentd-gcp](https://github.com/kubernetes/kubernetes/blob/59405cc2b437de501ef1f129952fcbf2a0115421/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L55)

you also need to adjust your values.yml . 

```
splunk-kubernetes-metrics:
...
  buffer:
  "@type": file
  "path": "/tmp/fluentd-buffers"
```

seems to reboot the container reliable when being in the stuck state.

**Comment by gnarc** [comment]
Since this is still a problem with 1.4.7 we decided to take a different path (OpenShift 4.6.x). It is still being tested and we do not know if this is valid. Maybe someone else ran into the same problem and had a different solution or has some insight why we should not do it this way?

1. activate the monitor_agent as described here: https://github.com/splunk/splunk-connect-for-kubernetes/issues/626
2. create a liveness probe, e.g. something like this:

```
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |-
              if [ ! -e /tmp/old ];
              then
                curl -sX GET  http://127.0.0.1:24220/api/plugins |grep splunk_hec | grep -oP "(?<=emit_count:)\\d+" > /tmp/old;
                sleep 3;
              fi;
              curl -sX GET  http://127.0.0.1:24220/api/plugins |grep splunk_hec | grep -oP "(?<=emit_count:)\\d+" > /tmp/new;
              [ "$(cat /tmp/old)" = "$(cat /tmp/new)" ];
              EC="$?";
              mv /tmp/new /tmp/old;
              if [ ${EC} -eq 0 ];
              then exit 1;
              else exit 0;
              fi;
          failureThreshold: 4
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 4
        name: splunk-fluentd-k8s-metrics
  ```
  (it's a dirty hack, I know)
  
So this will basically compare two values from the monitor_agent endpoint and see if they do not change any more thus embrace that the process does no longer work

```
#   oc rsh  splunk-connect-splunk-kubernetes-metrics-t48rr   bash -c ' curl -sX GET  http://127.0.0.1:24220/api/plugins |grep splunk_hec |grep -oP "(?<=emit_count:)\\d+"; cat /tmp/old'
468435
462487
```

In our environment (or in general) this does not make sense for the objects pod since changes in the emit_count are less frequent.
