### ISSUE TITLE
No metrics data received 

### ISSUE THREAD

**Issue by yiren1105** [splunk/splunk-connect-for-kubernetes#503]
**What happened**: I deployed splunk-connect-for kubernetes to managed splunk cloud. I have created 3 indices for logging, metrics, and objects. The logging and objects have received data while the metrics are not getting any data from k8s.

**What you expected to happen**: kubernetes_metrics start to receive data 

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:
```
splunk-kubernetes-metrics:
  kubernetes:
    insecureSSL: true
  splunk:
    hec:
      indexName: kubernetes_metrics 
```
If I set insecureSSL as true, it will report cert issue.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Ruby version (use `ruby --version`):
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
- OS (e.g: `cat /etc/os-release`):
- Splunk version: Splunk Cloud 8.1.2009
- Splunk Connect for Kubernetes helm chart version: 1.4.3
- Others: aks

**Comment by yiren1105** [comment]
```
2020-11-23 17:03:16 +0000 [info]: starting fluentd-1.9.1 pid=1 ruby="2.5.5"
2020-11-23 17:03:16 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "-r/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/setup", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "--under-supervisor"]
fatal: not a git repository (or any of the parent directories): .git
2020-11-23 17:03:20 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2020-11-23 17:03:20 +0000 [info]: adding filter pattern="kube.cluster.**" type="record_modifier"
2020-11-23 17:03:20 +0000 [info]: adding filter pattern="kube.namespace.**" type="record_modifier"
2020-11-23 17:03:20 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2020-11-23 17:03:20 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2020-11-23 17:03:20 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2020-11-23 17:03:20 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2020-11-23 17:03:20 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2020-11-23 17:03:20 +0000 [info]: adding source type="kubernetes_metrics_aggregator"
2020-11-23 17:03:22 +0000 [info]: #0 starting fluentd worker pid=11 ppid=1 worker=0
2020-11-23 17:03:22 +0000 [info]: #0 fluentd worker is now running worker=0
```

**Comment by rockb1017** [comment]
Hello,

Are you querying metrics like in this doc?
https://docs.splunk.com/Documentation/Splunk/8.1.0/Metrics/Search

**Comment by yiren1105** [comment]
> Hello,
> 
> Are you querying metrics like in this doc?
> https://docs.splunk.com/Documentation/Splunk/8.1.0/Metrics/Search

Yes, however, there was no event ever received on my metrics index `kubernetes_metrics`. I was looking for a solution to get metrics data.

**Comment by matthewmodestino** [comment]
is the index a metrics index? based on your logs it seems to be happily sending....can you please double check both your metrics and metrics-agg pods for any errors and run:

```
| mcatalog values(metric_name) WHERE index=* by host
```

**Comment by yiren1105** [comment]
> is the index a metrics index? based on your logs it seems to be happily sending....can you please double check both your metrics and metrics-agg pods for any errors and run:
> 
> ```
> | mcatalog values(metric_name) WHERE index=* by host
> ```

Yes, I have 2 event indices for logging and objects, both of them are working fine. I have one metrics index for the above issue, which doesn't seem to be working. I have seen the following errors 
```
tags: ${{env.GIT_SHORT_SHA}}

**Comment by yiren1105** [comment]
> is the index a metrics index? based on your logs it seems to be happily sending....can you please double check both your metrics and metrics-agg pods for any errors and run:
> 
> ```
> | mcatalog values(metric_name) WHERE index=* by host
> ```
The same error still exists. After about an hour of deployment, the metrics pods started reporting these errors. No metric data indexed into my Splunk metric index. 
```
2020-12-04 15:03:23 +0000 [info]: starting fluentd-1.9.1 pid=1 ruby="2.5.5"
2020-12-04 15:03:23 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "-r/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/setup", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "--under-supervisor"]
fatal: not a git repository (or any of the parent directories): .git
2020-12-04 15:03:26 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2020-12-04 15:03:26 +0000 [info]: adding filter pattern="kube.cluster.**" type="record_modifier"
2020-12-04 15:03:26 +0000 [info]: adding filter pattern="kube.namespace.**" type="record_modifier"
2020-12-04 15:03:26 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2020-12-04 15:03:26 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2020-12-04 15:03:26 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2020-12-04 15:03:26 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2020-12-04 15:03:26 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2020-12-04 15:03:27 +0000 [info]: adding source type="kubernetes_metrics_aggregator"
2020-12-04 15:03:28 +0000 [info]: #0 starting fluentd worker pid=11 ppid=1 worker=0
2020-12-04 15:03:28 +0000 [info]: #0 fluentd worker is now running worker=0
2020-12-04 16:04:18 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `fetch' for nil:NilClass>
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:578:in `block (3 levels) in process_resource_usage_res'
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:577:in `each'
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:577:in `block (2 levels) in process_resource_usage_res'
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:566:in `each'
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:566:in `block in process_resource_usage_res'
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:565:in `synchronize'
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:565:in `process_resource_usage_res'
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:554:in `handle_resource_usage_response'
  2020-12-04 16:04:18 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-k8s-metrics-agg-1.1.4/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:543:in `scrape_resource_usage_metrics'
  2020-12-04 16:04:18 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-12-04 16:04:18 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-12-04 16:04:18 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-12-04 16:04:18 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-12-04 16:04:18 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-12-04 17:20:22 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `fetch' for nil:NilClass>
  2020-12-04 17:20:22 +0000 [error]: #0 suppressed same stacktrace
2020-12-04 17:42:19 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `fetch' for nil:NilClass>
  2020-12-04 17:42:19 +0000 [error]: #0 suppressed same stacktrace
2020-12-04 18:04:21 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `fetch' for nil:NilClass>
  2020-12-04 18:04:21 +0000 [error]: #0 suppressed same stacktrace
2020-12-04 18:10:18 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `fetch' for nil:NilClass>
  2020-12-04 18:10:18 +0000 [error]: #0 suppressed same stacktrace
2020-12-04 18:18:21 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `fetch' for nil:NilClass>
  2020-12-04 18:18:21 +0000 [error]: #0 suppressed same stacktrace
2020-12-04 19:34:20 +0000 [error]: #0 Failed to scrape resource usage metrics, error=, #<NoMethodError: undefined method `fetch' for nil:NilClass>
  2020-12-04 19:34:20 +0000 [error]: #0 suppressed same stacktrace
```

**Comment by adecchi-2inno** [comment]
@matthewmodestino 
Thank you for your reply.
I have a similar behaviour, it looks like it is everything ok with the config, but I can not see the metrics in splunk cloud.
The index configuration that I created is **metric** type, then in **App Context** I select **Search & Reporting**  then in splunk cloud is required to specify the data type from many option listed, so I choose one of of them. 
After that, I create some test with curl and the data is the index only if i specify a **metric_name** if we do not specify it the metric in sent but it does not exist in splunk.
So, probably splunk connect is sending the metric but without a **metric_name** , is a way to specify it ?

[info]: starting fluentd-1.9.1 pid=1 ruby="2.5.5"
[info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "-r/usr/local/share/gems/gems/bundler-2.2.4/lib/bundler/setup", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "--under-supervisor"]
[info]: adding filter pattern="kube.**" type="record_modifier"
[info]: adding filter pattern="kube.node.**" type="record_modifier"
[info]: adding filter pattern="kube.pod.**" type="record_modifier"
[info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
[info]: adding filter pattern="kube.container.**" type="record_modifier"
[info]: adding match pattern="kube.**" type="splunk_hec"
[info]: adding source type="kubernetes_metrics"
[info]: #0 Use URL https://X.X.X.X:10250/stats/summary for creating client to query kubelet summary api
[info]: #0 Use URL https://X.X.X.X:10250/stats for creating client to query kubelet stats api
[info]: #0 Use URL https://X.X.X.X:10250/metrics/cadvisor for creating client to query cadvisor metrics api
[warn]: parameter 'cluster_name' in <source>
