### ISSUE TITLE
Metrics fails with RestClient::NotFound error="404 Not Found"

### ISSUE THREAD

**Issue by JesperBerggren** [splunk/splunk-connect-for-kubernetes#505]
Hello everybody,

We're running a Kubernetes cluster based on Microk8s nodes.
Currently we're implementing the integration to Splunk via splunk-connect-for-kubernetes.

We have the logging and objects up and running with success, but the metrics is failing.

We installed splunk-connect-for-kubernetes via Helm with the the following values (selected relevant parts only):
```
global:
  logLevel: info
  splunk:
    hec:
      # host is required and should be provided by user
      host: "xxx"
      # port to HEC, optional, default 8088
      port: 8088
      # token is required and should be provided by user
      token: "xxx"
      # protocol has two options: "http" and "https", default is "https"
      protocol: "https"
      # indexName tells which index to use, this is optional. If it's not present, will use "main".
      indexName:
      # insecureSSL is a boolean, it indicates should it allow inscure SSL connection (when protocol is "https"). Default is false.
      insecureSSL: true
      # The PEM-format CA certificate for this client.
      # NOTE: The content of the certificate itself should be used here, not the file path.
      #       The certificate will be stored as a secret in kubernetes.
      clientCert: |
        -----BEGIN CERTIFICATE-----
        xxx
        -----END CERTIFICATE-----
      # The private key for this client.
      # NOTE: The content of the key itself should be used here, not the file path.
      #       The key will be stored as a secret in kubernetes.
      clientKey: |
        -----BEGIN PRIVATE KEY-----
        xxx
        -----END PRIVATE KEY-----
      # The PEM-format CA certificate file.
      # NOTE: The content of the file itself should be used here, not the file path.
      #       The file will be stored as a secret in kubernetes.
      caFile: |
        -----BEGIN CERTIFICATE-----
        xxx
        -----END CERTIFICATE-----
      # For object and metrics
      indexRouting:
  kubernetes:
    # The cluster name used to tag logs. Default is cluster_name
    clusterName: "xxx"
    # Add privileged access to containers for openshift compatability
    openshift: false
  prometheus_enabled:

...

splunk-kubernetes-metrics:
  enabled: true
  ...
  # = Kubernetes Connection Configs =
  kubernetes:
    # The hostname or IP address that kubelet will use to connect to. If not supplied, status.hostIP of the node is used to fetch metrics from the Kubelet API (via the $KUBERNETES_NODE_IP environment variable).
    # Default is "#{ENV['KUBERNETES_NODE_IP']}"
    kubeletAddress:
    # The port that kubelet is listening on. Default is 10250
    kubeletPort:
    # The port that is used to get the metrics using apiserver proxy using ssl for the metrics aggregator
    kubeletPortAggregator:
    # This option is used to get the metrics from summary api on each kubelet using ssl
    useRestClientSSL: true
    # if insecureSSL is set to true, insecure HTTPS API call is allowed, default false
    insecureSSL: true
    # Path to the CA file.
    caFile:
    # Path to the file contains the API token. By default it reads from the file "token" in the `secret_dir`.
    bearerTokenFile:
    # Path of the location where pod's service account's credentials are stored. Usually you don't need to care about this config, the default value should work in most cases.
    secretDir:
    # The cluster name used to tag cluster metrics from the aggregator. Default is cluster_name
    clusterName:
    # Add privileged access to containers for openshift compatability`
```

**What happened**:
Log from metrics pod:
```
2020-11-27 08:32:31 +0000 [info]: adding source type="kubernetes_metrics"
2020-11-27 08:32:32 +0000 [info]: #0 Use URL https://192.168.0.2:10250/stats/summary for creating client to query kubelet summary api
2020-11-27 08:32:32 +0000 [info]: #0 Use URL https://192.168.0.2:10250/stats for creating client to query kubelet stats api
2020-11-27 08:32:32 +0000 [info]: #0 Use URL https://192.168.0.2:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2020-11-27 08:32:32 +0000 [warn]: parameter 'cluster_name' in <source>
  @type kubernetes_metrics
  tag "kube.*"
  node_name "xxx"
  use_rest_client_ssl true
  insecure_ssl true
  cluster_name xxx
  interval 15s
</source> is not used.
2020-11-27 08:32:32 +0000 [info]: #0 starting fluentd worker pid=10 ppid=1 worker=0
2020-11-27 08:32:32 +0000 [info]: #0 fluentd worker is now running worker=0
2020-11-27 08:32:48 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=RestClient::NotFound error="404 Not Found"
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/ruby/net/http.rb:910:in `start'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:233:in `_follow_redirection'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:145:in `follow_redirection'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:121:in `return!'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/ruby/net/http.rb:910:in `start'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
  2020-11-27 08:32:48 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-kubernetes-metrics-1.1.4/lib/fluent/plugin/in_kubernetes_metrics.rb:647:in `scrape_stats_metrics'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-11-27 08:32:48 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```
Notice the:
_2020-11-27 08:32:48 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=RestClient::NotFound error="404 Not Found"_

**What you expected to happen**:
I expected metrics to be sent to Splunk...

**How to reproduce it (as minimally and precisely as possible)**:
As described, I think.

**Anything else we need to know?**:
Unknown right now.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-34+9e8b6537ec8b6f", GitCommit:"9e8b6537ec8b6f45c8e04a481350def07f5f761d", GitTreeState:"clean", BuildDate:"2020-11-05T18:58:59Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-34+9e8b6537ec8b6f", GitCommit:"9e8b6537ec8b6f45c8e04a481350def07f5f761d", GitTreeState:"clean", BuildDate:"2020-11-05T19:00:24Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Ruby version (use `ruby --version`):
Not installed

- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Splunk version:
```
Splunk
Version:
8.1.0
Build:
f57c09e87251
```

- Splunk Connect for Kubernetes helm chart version:
```
$ helm show chart splunk/splunk-connect-for-kubernetes
apiVersion: v1
appVersion: 1.4.3
dependencies:
- condition: splunk-kubernetes-logging.enabled
  name: splunk-kubernetes-logging
  repository: https://splunk.github.io/splunk-connect-for-kubernetes/
  version: 1.4.3
- condition: splunk-kubernetes-objects.enabled
  name: splunk-kubernetes-objects
  repository: https://splunk.github.io/splunk-connect-for-kubernetes/
  version: 1.4.3
- condition: splunk-kubernetes-metrics.enabled
  name: splunk-kubernetes-metrics
  repository: https://splunk.github.io/splunk-connect-for-kubernetes/
  version: 1.4.3
description: Collect logs, objects (metadata), and metrics with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/main/helm-chart
keywords:
- splunk
- monitoring
- logging
- metrics
- metadata
- objects
maintainers:
- email: DataEdge@splunk.com
  name: Splunk Inc.
name: splunk-connect-for-kubernetes
sources:
- https://github.com/splunk/splunk-connect-for-kubernetes/tree/main/helm-chart
- https://github.com/splunk/fluent-plugin-splunk-hec
- https://github.com/splunk/fluent-plugin-kubernetes-metrics
- https://github.com/splunk/fluent-plugin-k8s-metrics-agg
- https://github.com/splunk/fluent-plugin-kubernetes-objects
version: 1.4.3
```

- Others:
N/A

**Comment by JesperBerggren** [comment]
As an update I've tried to curl to the listed endpoints:
```
2020-11-27 08:32:32 +0000 [info]: #0 Use URL https://192.168.0.2:10250/stats/summary for creating client to query kubelet summary api
2020-11-27 08:32:32 +0000 [info]: #0 Use URL https://192.168.0.2:10250/stats for creating client to query kubelet stats api
2020-11-27 08:32:32 +0000 [info]: #0 Use URL https://192.168.0.2:10250/metrics/cadvisor for creating client to query cadvisor metrics api
```
```
$ curl -sSLk https://192.168.0.2:10250/stats/summary
Unauthorized
$ curl -sSLk https://192.168.0.2:10250/stats
Unauthorized
$ curl -sSLk https://192.168.0.2:10250/metrics/cadvisor
Unauthorized
```
If I on the other hand tries to curl to the root of the kubelet endpoint I get:
```
$ curl -sSLk https://192.168.0.2:10250/
404 page not found
```
To me it looks like the _stats_metric_scraper_ it trying to connect to some non-existing endpoint but the log doesn't state which endpoint it's trying to connect to when failing.

Any insight anyone?

Best regards
Jesper

**Comment by schose** [comment]
Most probably an ssl issue as you get an answer from the 10250 port and use curl -k option. Try to set

```
splunk-kubernetes-metrics:
  kubernetes:
    insecureSSL: true 
```

Best Regards,

Andreas

**Comment by JesperBerggren** [comment]
I very much doubt it has anything to do with TLS because I have already turned on:
```
splunk-kubernetes-metrics:
  kubernetes:
    insecureSSL: true
```

If I set it to false I get the following error:
```
020-11-30 19:22:37 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=RestClient::SSLCertificateNotVerified error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)"
```
which seems to be quite a normal problem for many.
I have found no similar issues or posts anywhere with my case: _error="404 Not Found"_
Is it possible to turn on some debugging to see which **path** stats_metric_scraper is trying to reach on https://{ENV['KUBERNETES_NODE_IP']}:10250/...?

Btw: Being worried that kubelet didn't have stats I've tried to explicitly setting _--enable-debugging-handlers=true_
That did not work either.

I've also tried to set:
```
splunk-kubernetes-metrics:
  kubernetes:
    kubeletPort: 10255
    useRestClientSSL: false
    insecureSSL:
```
This actually ends up with the same error:
```
2020-11-30 19:48:23 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=RestClient::NotFound error="404 Not Found"
```

Anybody?

Best regards
Jesper

**Comment by JesperBerggren** [comment]
So while running with:
```
splunk-kubernetes-metrics:
  kubernetes:
    kubeletPort: 10255
    useRestClientSSL: false
    insecureSSL:
```
I was able to do a _sudo tcpdump -i cni0 -n port 10255 -w kubelet.pcap_
This allowed me to see that the following paths works:

- /stats/summary   200 OK
- /metrics/cadvisor    200 OK


But it fails on this path:

- /stats    301 Moved Permanently (first try)
- /stats    404 Not Found (second try)

Can I be anything with **authorization**?
I've not really set too many values for the Helm Chart:
```
splunk-kubernetes-metrics:
  enabled: true
...
  rbac:
    # Specifies whether RBAC resources should be created.
    # This should be set to `false` if either:
    # a) RBAC is not enabled in the cluster, or
    # b) you want to create RBAC resources by yourself.
    create: true
...
  # = Kubernetes Connection Configs =
  kubernetes:
    # The hostname or IP address that kubelet will use to connect to. If not supplied, status.hostIP of the node is used to fetch metrics from the Kubelet API (via the $KUBERNETES_NODE_IP environment variable).
    # Default is "#{ENV['KUBERNETES_NODE_IP']}"
    kubeletAddress: xxx
    # The port that kubelet is listening on. Default is 10250
    kubeletPort: 10255
    # The port that is used to get the metrics using apiserver proxy using ssl for the metrics aggregator
    kubeletPortAggregator: 10250
    # This option is used to get the metrics from summary api on each kubelet using ssl
    useRestClientSSL: false
    # if insecureSSL is set to true, insecure HTTPS API call is allowed, default false
    insecureSSL:
    # Path to the CA file.
    caFile:
    # Path to the file contains the API token. By default it reads from the file "token" in the `secret_dir`.
    bearerTokenFile:
    # Path of the location where pod's service account's credentials are stored. Usually you don't need to care about this config, the default value should work in most cases.
    secretDir:
    # The cluster name used to tag cluster metrics from the aggregator. Default is cluster_name
    clusterName: "servicemesh.udviklersandkassen"
    # Add privileged access to containers for openshift compatability
    openshift: false
```
PS: I intend to change it back to useRestClientSSL: true but for now it's easier to debug without TLS.

Any thoughts now?

Best regards
Jesper

**Comment by iLearn404** [comment]
Hi Jesper,

If it helps -- I'm also receiving the same error messages in Splunk on SCK 1.4.3 and actively looking to resolve it too. I'm in the process of turning on the logLevel in values.yaml to debug for the applicable chart(s) in the hopes it gives more context.

Sample of Error Logs:
`2020-11-27 15:22:24 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-kubernetes-metrics-1.1.4/lib/fluent/plugin/in_kubernetes_metrics.rb:647:in `scrape_stats_metrics'
2020-11-27 15:22:24 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=RestClient::NotFound error="404 Not Found"
2020-11-27 15:22:22 +0000 [error]: #0 Timer detached. title=:stats_metric_scraper
`

When stated, "We have the logging and objects up and running with success, but the metrics is failing", are you not getting any metric logs or only partial? We seem to still be receiving almost all metrics and haven't pinpointed which dimension or metrics might be missing.

Splunk Query:
`| mcatalog values(_dims) as dims values(metric_name) as metric_name  WHERE index=* cluster_name=* by cluster_name
| stats  values(dims) as dims values(metric_name) as metric_name dc(dims) as dc_Dims dc(metric_name) as dcMetric_name by cluster_name`

**Comment by JesperBerggren** [comment]
Thanks for chipping in! And it does help because it increases the chance that we haven't made some terrible mistake when initially defining the cluster and/or configuring SCK.

Good point. We're actually getting partial metrics as well, even though I'm unsure about the coverage.

Let me know if you make further results in your investigations and I will do the same.

**Comment by JesperBerggren** [comment]
Ok, I've been digging in rbac setup for metrics even though I would suspect it should return a _403 Forbidden_ if rbac was the culprit.

I have this clusterrole defined:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: atp-splunk-connect
    meta.helm.sh/release-namespace: splunk
  ...
  name: kubelet-summary-api-read
  ...
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/stats
  - nodes/metrics
  verbs:
  - get
```
NB! Notice that the _nodes/stats_ is allowed/defined, which is nevertheless returning 404.

Furthermore I have this clusterrolebinding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: atp-splunk-connect
    meta.helm.sh/release-namespace: splunk
  ...
  name: atp-splunk-connect-splunk-kubernetes-metrics
  ...
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-summary-api-read
subjects:
- kind: ServiceAccount
  name: atp-splunk-connect-splunk-kubernetes-metrics
  namespace: splunk
```

And I have this serviceaccount:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: atp-splunk-connect
    meta.helm.sh/release-namespace: splunk
  ...
  name: atp-splunk-connect-splunk-kubernetes-metrics
secrets:
- name: atp-splunk-connect-splunk-kubernetes-metrics-token-crhpn
```

And finally I have the secret:
```
apiVersion: v1
data:
  ca.crt: xxx
  namespace: xxx
  token: xxx
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: atp-splunk-connect-splunk-kubernetes-metrics
  ...
  name: atp-splunk-connect-splunk-kubernetes-metrics-token-crhpn
  ...
type: kubernetes.io/service-account-token
```

To me it looks alright and as intially stated I would suspect a 403 instead of 404.

**Comment by JesperBerggren** [comment]
Solved, kind of!

I found that setting:
**--enable-cadvisor-json-endpoints=true**
in kubelet config fixed the error.

But according to [https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/):

> --enable-cadvisor-json-endpoints     Default: `false`
>    Enable cAdvisor json `/spec` and `/stats/*` endpoints. (DEPRECATED: will be removed in a future version)


What does it mean that it will be deprecated soon?

Is SCK using an API that is about to be deprecated???

**Comment by rockb1017** [comment]
Thanks @JesperBerggren for sharing your detailed information and what made it work for you.
SCK collects cAdvisor metrics endpoints. 
we will add more metrics collection methods as they become available. Thanks!

**Comment by adecchi-2inno** [comment]
@JesperBerggren 
Could you fix it ? I got the same problem
`[error]: #0 Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=RestClient::BadRequest error="400 Bad Request"`
What value, should I configure in the values.yaml to fix this problem ?

**Comment by atp-integration-mesh** [comment]
Hi adecchi-2inno,

You can't fix the problem in the values.yaml file.
It's a configuration issue in Kubernetes and must be fixed in the kubelet configuration.

As stated above I'm running a Microk8s cluster and it's installed via snap, so my kubelet configuration is done in this file:
**/var/snap/microk8s/current/args/kubelet**
I added the following line:
**--enable-cadvisor-json-endpoints=true**

Hope that helps.
Regards, Jesper

**Comment by adecchi-2inno** [comment]
HI @atp-integration-mesh 
Thank you for your reply.
I am using EKS 1.18 and Splunk Forwarder 1.4.3, when I found this issue.
do you know, what is the workaround, to get the metrics ? Without this performance data really, i am blindly

**Comment by atp-integration-mesh** [comment]
Hi again,

I've not used EKS but I would guess you should use **update-kubeconfig** as described in [https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html](https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html)

Regards
Jesper

**Comment by X-dark** [comment]
> Thanks @JesperBerggren for sharing your detailed information and what made it work for you.
> SCK collects cAdvisor metrics endpoints.
> we will add more metrics collection methods as they become available. Thanks!

Any work on switching to an existing endpoint or at least switching off removed one?

**Comment by rockb1017** [comment]
we welcome contributions! 
but, internally we are planning to use open telemetry agent instead of fluentd.

**Comment by keenan-wells-dxc** [comment]
Thanks you @JesperBerggren for digging into this as much as you have. I'm also running into this error, will try the solution for enabling cAdvisor endpoints on kubelets, but would appreciate a better solution than this if it's available in the near future if one becomes available.
