### ISSUE TITLE
got unrecoverable error in primary and no secondary error_class=ArgumentError error="header field value cannot include CR/LF"

### ISSUE THREAD

**Issue by jaypalpatil** [splunk/splunk-connect-for-kubernetes#563]
**After deployment of splunk-kubernetes-logging manifest files, I am getting the below error in fluentd :**

2021-02-22 07:33:57	+0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="header field value cannot include CR/LF"
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/ruby/net/http/header.rb:84:in `set_field'
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/ruby/net/http/header.rb:49:in `[]='
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/ruby/net/http/generic_request.rb:73:in `[]='
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/gems/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:1044:in `block in request_setup'
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/gems/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:1043:in `each'
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/gems/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:1043:in `request_setup'
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/gems/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:955:in `request'
2021-02-22 07:33:57 +0000 [warn]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.4/lib/fluent/plugin/out_splunk_hec.rb:302:in `write_to_splunk'
2021-02-22 07:33:57 +0000 [warn]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.4/lib/fluent/plugin/out_splunk.rb:97:in `block in write'
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/ruby/benchmark.rb:308:in `realtime'
2021-02-22 07:33:57 +0000 [warn]: #0 /opt/app-root/src/gem/fluent-plugin-splunk-hec-1.2.4/lib/fluent/plugin/out_splunk.rb:96:in `write'
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/compat/output.rb:131:in `write'
2021-02-22 07:33:57 +0000 [warn]: #0 /usr/share/

Can someone pls suggest how to resolve this issue..??

**Comment by jaypalpatil** [comment]
Also pls help me to understand why this issue occurred... Many Thanks in Advance..!!

**Comment by vinzent** [comment]
please share your values.yml, which splunk-connect version (1.x.x) , what kubernetes platform (openshift, rancher, ...)

**Comment by jaypalpatil** [comment]
Hi Thomas,

I am not using the values.yml file; directly deployed the 'splunk-kubernetes-logging' manifest files.

splunk-connect version is 1.4.6. And we are using PKS Dev kubernetes, the version is 1.8.

**Comment by vinzent** [comment]
> directly deployed the 'splunk-kubernetes-logging' manifest files.

which "manifest" files? did you run helm to deploy? what values have you provided with `--set` ?

**Comment by jaypalpatil** [comment]
Hi,

**Steps I have followed:**

1. Downloaded the complete package of 'splunk-connect-for-kubernetes'
2. After that used file from 'splunk-connect-for-kubernetes/manifests/splunk-kubernetes-logging/'. 
3. Updated the splunk, hec details, etc in all those manifest files
4. Deployed the updated only logging manifest files in kubernetes

**Comment by jaypalpatil** [comment]
Kindly find the attached manifest files which I have used in deployment.

[splunk_logging-manifest_files.zip](https://github.com/splunk/splunk-connect-for-kubernetes/files/6021698/splunk_logging-manifest_files.zip)

**Comment by vinzent** [comment]
Alright, i've only ever used it by the helm way. IMHO: the helm way is superior because you have better lifecycle support (update, upgrade, rollback, ..).

**Comment by jaypalpatil** [comment]
Okk... Can you help with my issue..??

**Comment by vinzent** [comment]
Just try deploying it with helm?

**Comment by jaypalpatil** [comment]
Okay, can you pls provide the exact step... It will be really helpful because I am not getting a clear understanding from the documentation...

**Comment by jaypalpatil** [comment]
Hi Thomas,

For now, HELM Deployment is not possible. Can you pls help me with the manifest deployment option..? Or maybe point to the correct person.

**Comment by vinzent** [comment]
on what part do you have issues? https://github.com/splunk/splunk-connect-for-kubernetes#deploy-with-helm 

I do not know PKS and what logging format it is using (docker or cri) and where additional audit files are.

here you can see an example from an OpenShift 4 cluster (Kubernetes 1.18): https://github.com/splunk/splunk-connect-for-kubernetes/pull/546/files

**Comment by vinzent** [comment]
> For now, HELM Deployment is not possible. Can you pls help me with the manifest deployment option..? Or maybe point to the correct person.

Maybe Splunk Support? i really don't know. I'm not from Splunk.

the error is abot CR/LF - somewhere you've got a linebreak where none should be or the manifests are not tested and they contain a bug.

**Comment by jaypalpatil** [comment]
I'll re-check this... Thank you..!!

**Comment by jaypalpatil** [comment]
This issue is resolved.

Solution : I was using the http in configMap.yaml file and in Splunk HEC Global settings 'SSL Connection was enabled'. So I disabled the SSL Connection.

Thank you..!!
