### ISSUE TITLE
Getting partial metrics from SCK on Openshift4.6

### ISSUE THREAD

**Issue by rupadhy3** [splunk/splunk-connect-for-kubernetes#582]
Issue with splunk-kubernetes-metrics:
Getting the below error with splunk-kubernetes-metrics and only partial metrics is being sent to splunk, with below error on splunk metrics pods:

I have seen other post where they mentioned a solution  to --enable-cadvisor-json-endpoints=true, but as we are using Openshift 4.6 and this parameter is being depricated and it cannot be applied to the kubelet config.

So is there any other solution for this to resolve. 

2021-03-11 09:24:50 +0000 [error]: #0 Timer detached. title=:stats_metric_scraper
  insecure_ssl true
  cluster_name Dev1cluster
  interval 15s
</source> is not used.
2021-03-11 09:25:01 +0000 [info]: #0 starting fluentd worker pid=11 ppid=1 worker=0
2021-03-11 09:25:01 +0000 [info]: #0 fluentd worker is now running worker=0
2021-03-11 09:25:20 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=RestClient::NotFound error="404 Not Found"
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/ruby/net/http.rb:910:in `start'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:233:in `_follow_redirection'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:145:in `follow_redirection'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:121:in `return!'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/ruby/net/http.rb:910:in `start'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
  2021-03-11 09:25:20 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-kubernetes-metrics-1.1.4/lib/fluent/plugin/in_kubernetes_metrics.rb:647:in `scrape_stats_metrics'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2021-03-11 09:25:20 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-03-11 09:25:20 +0000 [error]: #0 Timer detached. title=:stats_metric_scraper

Environment:
Openshift Server Version: 4.6.4
Kubernetes Version: v1.19.0+9f84db3
cri-o://1.19.0-22.rhaos4.6.gitc0306f1.el8

**Comment by harshit-splunk** [comment]
From the k8s v1.15, the 'stats' endpoint was deprecated along with few other endpoints providing metrics data in JSON format from cAdvisor. It has been disabled by default from v1.18 onwards and removed from v1.21 onwards.
So, added checking availability of stats endpoint before starting scrapping from stats endpoint.
Ref: https://github.com/splunk/fluent-plugin-kubernetes-metrics/pull/102
