### ISSUE TITLE
Unable to send metrics logs

### ISSUE THREAD

**Issue by NitinVPandey** [splunk/splunk-connect-for-kubernetes#614]
**What happened**:
Deployed splunk connect using helm, used cutom values.yaml file. Pods got deployed.

**What you expected to happen**:
Splunk connect pods were not able to send logs to splunk. When checked the pod logs  found below messages.
2021-06-07 04:35:45 +0000 [warn]: #0 [containers.log] pattern not matched: "2021-06-07T04:35:39.217085832Z stdout F 2021-06-07
 04:35:39 +0000 [warn]: #0 [containers.log] pattern not matched: \"2021-06-07T04:35:36.230272939Z stdout F 2021-06-07 04:35:36
 +0000 [warn]: #0 [containers.log] pattern not matched: \\\"2021-06-07T04:35:33.793318132Z stdout F 2021-06-07 04:35:33 +0000 
[warn]: #0 [containers.log] pattern not matched: \\\\\\\"2021-06-07T04:35:21.280735776Z stdout F 2021-06-07 04:35:21 +0000 [wa
rn]: #0 [containers.log] pattern not matched: \\\\\\\\\\\\\\\"2021-06-07T04:35:14.737816121Z stdout F 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Splunk Connect for Kubernetes helm chart version:
- Others:

**Comment by gp510** [comment]
@NitinVPandey - Can you share your values.yaml file?

**Comment by NitinVPandey** [comment]
yes below is the value.yaml file.
I was able to deploy pods for charts splunk-kubernetes-logging and splunk-kubernetes-objects and send logs to splunk cloud.
Getting error in pods for chart splunk-kubernetes-metrics. The error is 
2021-06-20 14:08:09 +0000 [info]: #0 starting fluentd worker pid=11 ppid=1 worker=0
2021-06-20 14:08:09 +0000 [info]: #0 fluentd worker is now running worker=0
2021-06-20 14:08:25 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=Res
tClient::NotFound error="404 Not Found"
  2021-06-20 14:08:25 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exc
eption_with_response'
  2021-06-20 14:08:25 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `ret
urn!'
  2021-06-20 14:08:25 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_resul
t'
  2021-06-20 14:08:25 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in tran
smit'
  2021-06-20 14:08:25 +0000 [error]: #0 /usr/share/ruby/net/http.rb:933:in `start'
  2021-06-20 14:08:25 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
  2021-06-20 14:08:25 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2021-06-20 14:08:25 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:233:in `_fo
llow_redirection'


Values.yaml is as below

global:
  logLevel: info
  splunk:
    hec:
      host: xxx.splunkcloud.com
      port: 8088
      token: xxxxx
      protocol: https
      insecureSSL: true
  kubernetes:
    clusterName: xxx
  prometheus_enabled: false
  monitoring_agent_enabled: false
splunk-kubernetes-logging:
  enabled: true
  fluentd:
    path: /var/log/containers/*.log
  containers:
    path: /var/log
    pathDest: /var/lib/docker/containers
    logFormatType: cri
  K8sMetadata:
     podLabels:
     - app
     - k8s-app
     - release
  splunk:
    hec:
     indexName: logs
  journalLogPath: /run/log/journal   
splunk-kubernetes-objects:
  enabled: true
  splunk:
    hec:
     indexName: objects
splunk-kubernetes-metrics:
  enabled: true
  splunk:
    hec:
     indexName: metrics
  kubernetes:
    useRestClientSSL: true
    insecureSSL: true

**Comment by NitinVPandey** [comment]
any help please, able to send pod logs and objects logs to splunk cloud, but not able to send  for metrics logs

**Comment by rockb1017** [comment]
are you using kubernetes version 1.21+ ? metrics endpoint it is using has been removed. so it is supported only upto 1.20

**Comment by NitinVPandey** [comment]
No my kubernetes version is 1.19.9

**Comment by rockb1017** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/issues/505#issuecomment-736473126
Have you tried enabling the endpoint ?

**Comment by NitinVPandey** [comment]
Do you mean enable metric endpoints on the cluster?

**Comment by rockb1017** [comment]
on the kubelet daemon. (take a read at the thread I linked)
