### ISSUE TITLE
kube-object image fail due to "v1 is forbidden: User cannot list resource" in OpenShift 4.10 cluster.

### ISSUE THREAD

**Issue by BrandonTsai** [splunk/splunk-connect-for-kubernetes#784]
**What happened**:

splunk-kubernetes-objects fail to get openshift resource status after upgrading from version 1.4.9 to 1.4.15

The pod is running , but showing following error message:

```
#<Thread:0x000056152a888ca0@pull_daemon_sets /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:130:in `rescue in handle_exception': v1 is forbidden: User "system:serviceaccount:splunk-connect:splunk-kubernetes-objects" cannot list resource "v1" in API group "" at the cluster scope (Kubeclient::HttpError)
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:120:in `handle_exception'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:596:in `fetch_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:583:in `load_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:134:in `discover'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:100:in `method_missing'
        from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.12/lib/fluent/plugin/in_kubernetes_objects.rb:207:in `public_send'
        from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.12/lib/fluent/plugin/in_kubernetes_objects.rb:207:in `block in create_pull_thread'
        from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
/usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 403 Forbidden (RestClient::Forbidden)
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
        from /usr/share/ruby/net/http.rb:933:in `start'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:596:in `block in fetch_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:121:in `handle_exception'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:596:in `fetch_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:583:in `load_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:134:in `discover'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:100:in `method_missing'
        from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.12/lib/fluent/plugin/in_kubernetes_objects.rb:207:in `public_send'
        from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.12/lib/fluent/plugin/in_kubernetes_objects.rb:207:in `block in create_pull_thread'
        from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-07-01 03:38:56 +0000 [error]: #0 unexpected error error_class=Kubeclient::HttpError error="HTTP status code 403, v1 is forbidden: User \"system:serviceaccount:splunk-connect:splunk-kubernetes-objects\" cannot list resource \"v1\" in API group \"\" at the cluster scope for GET https://172.30.0.1/api/apps/v1"
#<Thread:0x000056152b2b2bb8@pull_deployments /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:130:in `rescue in handle_exception': v1 is forbidden: User "system:serviceaccount:splunk-connect:splunk-kubernetes-objects" cannot list resource "v1" in API group "" at the cluster scope (Kubeclient::HttpError)
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:120:in `handle_exception'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:596:in `fetch_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:583:in `load_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:134:in `discover'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:100:in `method_missing'
        from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.12/lib/fluent/plugin/in_kubernetes_objects.rb:207:in `public_send'
        from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.12/lib/fluent/plugin/in_kubernetes_objects.rb:207:in `block in create_pull_thread'
        from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
/usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 403 Forbidden (RestClient::Forbidden)
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
        from /usr/share/ruby/net/http.rb:933:in `start'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
        from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:596:in `block in fetch_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:121:in `handle_exception'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:596:in `fetch_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:583:in `load_entities'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:134:in `discover'
        from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:100:in `method_missing'
        from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.12/lib/fluent/plugin/in_kubernetes_objects.rb:207:in `public_send'
        from /opt/app-root/src/gem/fluent-plugin-kubernetes-objects-1.1.12/lib/fluent/plugin/in_kubernetes_objects.rb:207:in `block in create_pull_thread'
        from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

This issue happen when using image splunk/kube-objects:1.1.11 and splunk/kube-objects:1.1.12
it works only if I use image splunk/kube-objects:1.1.10 

**What you expected to happen**:

The new image should work correctly in OpenShift 4.10 and the pod should fail if there is unexpected error!

**How to reproduce it (as minimally and precisely as possible)**:

Deploy splunk-connect-for-k8s on OpenShift 4.10 cluster

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): OpenShift 4.10 cluster
- OS (e.g: `cat /etc/os-release`):
CoreOS
- Splunk version: 
Splunk Enterprise
Version:
8.1.2
Build:
545206cc9f70

- Splunk Connect for Kubernetes helm chart version: 1.4.15

- Others:

[splunk-connect-objects-1.4.15.logs.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/9024977/splunk-connect-objects-1.4.15.logs.txt)
[configmap-splunk-connect-objects-1.4.15.yaml.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/9024979/configmap-splunk-connect-objects-1.4.15.yaml.txt)

**Comment by harshit-splunk** [comment]
Hi @BrandonTsai,
`2022-07-01 03:38:56 +0000 [error]: #0 unexpected error error_class=Kubeclient::HttpError error="HTTP status code 403, v1 is forbidden: User \"system:serviceaccount:splunk-connect:splunk-kubernetes-objects\" cannot list resource \"v1\" in API group \"\" at the cluster scope for GET https://172.30.0.1/api/apps/v1"` suggests that `system:serviceaccount:splunk-connect:splunk-kubernetes-objects` doesn't have access to those objects.

Were you facing this issue immediately after upgrading the collector or after some time?
